### ISSUE TITLE
Debug adapter process has terminated unexpectedly

### ISSUE THREAD

**Issue by aitorllj93** [Microsoft/vscode-cordova#26] opened 2016-01-29 14:52 UTC
On Linux Mint 17.2

Also, the Cordova:Run and Cordova:Build commands return
```
No handler found for the command: 'cordova.run'. Ensure there is an activation event defined, if you are an extension.
```

The cordova application was succesful created an built from command line for android platform. Only fails on vscode.

## launch.json
```json
{
	"version": "0.2.0",
	"configurations": [
         {
            "name": "Cordova",
            "type": "cordova",
            "request": "launch",
            "platform": "android",
            "target": "device"
        }
	]
}
```

## config.xml
```xml
<?xml version='1.0' encoding='utf-8'?>
<widget id="com.test.package" version="1.0.0" xmlns="http://www.w3.org/ns/widgets" xmlns:cdv="http://cordova.apache.org/ns/1.0">
    <name>gxdcalidad</name>
    <description>
        A sample Apache Cordova application that responds to the deviceready event.
    </description>
    <author email="dev@cordova.apache.org" href="http://cordova.io">
        Apache Cordova Team
    </author>
    <content src="index.html" />
    <access origin="*" />
    <preference name="Fullscreen" value="true" />
    <preference name="DisallowOverscroll" value="true" />
    <engine name="android" spec="~4.1.1" />
    <plugin name="com.lampa.startapp" spec="~0.0.5" />
    <plugin name="cordova-plugin-whitelist" spec="1" />
    <allow-navigation href="*" />
    <allow-intent href="http://*/*" />
    <allow-intent href="https://*/*" />
    <allow-intent href="tel:*" />
    <allow-intent href="sms:*" />
    <allow-intent href="mailto:*" />
    <allow-intent href="geo:*" />
    <platform name="android">
        <allow-intent href="market:*" />
    </platform>
    <platform name="ios">
        <allow-intent href="itms:*" />
        <allow-intent href="itms-apps:*" />
    </platform>

</widget>
```

## Distro details

```
::::::::::::::
/etc/lsb-release
::::::::::::::
DISTRIB_ID=LinuxMint
DISTRIB_RELEASE=17.2
DISTRIB_CODENAME=rafaela
DISTRIB_DESCRIPTION="Linux Mint 17.2 Rafaela"
::::::::::::::
/etc/os-release
::::::::::::::
NAME="Ubuntu"
VERSION="14.04.3 LTS, Trusty Tahr"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 14.04.3 LTS"
VERSION_ID="14.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"

*** /etc/upstream-release: directory ***
```

## Linux Kernel

```
3.16.0-38-generic
```

## Cordova
```
5.4.1
```

### Android (adb)
```
Android Debug Bridge version 1.0.32
Revision 09a0d98bebce-android
```

**Comment by MSLaguana** [comment] 2016-01-29 17:28
Apologies for this, looks like we have some file casing issues which are stopping the extension from loading properly. Thanks for letting us know!

**Comment by MSLaguana** [comment] 2016-02-03 23:24
This should be fixed in our next release.

**Closed by MSLaguana** 2016-02-03 23:24 UTC
Labels: bug

**Comment by mikaoelitiana** [comment] 2016-06-01 05:55
Hello, 
I have the same error on Mac with version 1.1.1 of the plugin. Am I missing something? I have Cordova 5.4.1 and node 0.12.9

**Comment by MSLaguana** [comment] 2016-06-01 06:04
What is the exact error you are getting and what are you doing when it happens? This specific issue was fixed.

**Comment by mikaoelitiana** [comment] 2016-06-01 06:09
I have the following errors for each task : 
`No handler found for the command: 'cordova.build'. An extension might be missing an activation event.`
`No handler found for the command: 'cordova.run'. An extension might be missing an activation event.`
`No handler found for the command: 'cordova.prepare'. An extension might be missing an activation event.`

<img width="1680" alt="capture d ecran 2016-06-01 a 09 06 45" src="https://cloud.githubusercontent.com/assets/674667/15699777/5cea1976-27d8-11e6-99a8-6a7e02c43f0b.png">

I must also say that my cordova project is not in the root folder but a sub-directory of the project (/phonegap). This may be the cause?

**Comment by MSLaguana** [comment] 2016-06-01 06:12
Yes, that would cause this. We only hook up the handlers it is referring to if we think you have opened a Cordova project in your workspace, and we base that on the root folder (If it has a config.xml for example).

Could you please open a separate issue about your specific problem, so it doesn't get lost?

**Comment by mikaoelitiana** [comment] 2016-06-01 06:13
Alright, I will do so. Thanks!!
