### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by MetalxD117** [Microsoft/vscode-cordova#516] opened 2019-04-08 03:06 UTC
- Issue Type: `Performance`
- Extension Name: `cordova-tools`
- Extension Version: `1.8.0`
- OS Version: `Windows_NT x64 6.3.9600`
- VSCode version: `1.33.0`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`C:\Users\JuanSebastian\vsmobile.cordova-tools-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/Microsoft/vscode/wiki/Explain:-extension-causes-high-cpu-load

**Comment by ruslan-bikkinin** [comment] 2019-04-08 13:59
Closed as duplicate of #517

**Closed by ruslan-bikkinin** 2019-04-08 13:59 UTC
Labels: duplicate
