### ISSUE TITLE
Cordova-tools error . The "path" argument must be of type string. Received type object

### ISSUE THREAD

**Issue by zhangshenghong** [microsoft/vscode-cordova#598] opened 2019-12-20 12:25 UTC
![image](https://user-images.githubusercontent.com/48314995/71254522-302b4580-2366-11ea-8f1a-6161c46f2823.png)
I use the default generated launch.json , but " Run Browser " is error .

Thanks for the help!

**Comment by zhangshenghong** [comment] 2019-12-20 12:29
- VSCode version: 1.41.1
- NodeJS version: v10.15.3
- Cordova version: 9.0.0
- Cordova Tools version:1.9.1

**Comment by SounD120** [comment] 2019-12-20 12:45
Hi @zhangshenghong and thanks for reaching us. Could you please make sure that your workspace root folder is a Cordova project? I was able to reproduce this in case if the opened workspace did not contain a Cordova project.

**Comment by zhangshenghong** [comment] 2019-12-23 02:27
I use Framework7-cli. Generated Cordova project. I changed the cwd path to `${workspacefolder}/Cordova/`. The result is a new error, as shown below.
![image](https://user-images.githubusercontent.com/48314995/71331822-b9ad6400-256e-11ea-971f-6303ecdc35f4.png)

**Comment by SounD120** [comment] 2019-12-23 07:19
@zhangshenghong As seen from your `launch.json` your `cwd` argument does not point to the workspace root. Could you please change `cwd` parameter to `"cwd": "${workspaceFolder}"` and try again? Please let us know if this helped.

**Comment by zhangshenghong** [comment] 2019-12-23 07:31
@SounD120 
This will cause the first error, because root folder is not a Cordova project

**Comment by SounD120** [comment] 2019-12-23 07:39
@zhangshenghong Oh I see, also it is needed to open `cordova` folder as a workspace folder using [multi-root workspaces](https://code.visualstudio.com/docs/editor/multi-root-workspaces) approach and create separate `launch.json` file in there. You can do this the following way:

1. Add `cordova` folder to your workspace using that [instruction](https://code.visualstudio.com/docs/editor/multi-root-workspaces)
1. Create `launch.json` file with debug configurations in `./cordova/.vscode` folder
1. Run `Run Browser (cordova)` debug scenario.

Could you please try to execute your application using the instruction above and let us know if this helped?

**Comment by zhangshenghong** [comment] 2019-12-23 07:53
@SounD120 In this way, VS code `DEBUG ADN RUN` still points to launch.json under root folder. Unless I use ` ./cordova` as a workspace.

**Comment by zhangshenghong** [comment] 2019-12-23 07:57
@SounD120 `./cordova` as a workspace folder, Run `Run Browser (cordova)` is OK.

**Comment by SounD120** [comment] 2019-12-23 08:12
@zhangshenghong Glad to hear that. With respect to the problem with incorrect folder pointing of `DEBUG AND RUN` view - it is a [VS Code bug](https://github.com/microsoft/vscode/issues/87237) that does not reproduce anymore on VS Code Insiders. That mean that it will be fixed in the future VS Code releases.
![image](https://user-images.githubusercontent.com/32372875/71344735-6a6a3200-2574-11ea-86a9-627140249a07.png)
It looks like the original issue has been resolved, so I am closing this issue. Please feel free to open new ones if needed.

**Closed by SounD120** 2019-12-23 08:12 UTC
Labels: waiting-for-clarification

**Comment by zhangshenghong** [comment] 2019-12-23 08:41
@SounD120 Oh, I see, thank you.
