### ISSUE TITLE
[cordova-debug-adapter] Error: connect ECONNREFUSED 127.0.0.1:9223

### ISSUE THREAD

**Issue by brusinow** [Microsoft/vscode-cordova#191] opened 2016-09-25 01:40 UTC
Am getting this error whenever I try to "run ios on simulator". This is with the default values from the Cordova debug tools in my launch.json (so port 9220 for "run ios on simulator"). These are my debug logs:
Launching for ios (This may take a while)...
Launching app (This may take a while)...
Starting Ionic dev server (live reload: true)
Building and deploying app
Attaching to ios
Configuring debugging proxy
Unable to communicate with target
connect ECONNREFUSED 127.0.0.1:9223

**Comment by MSLaguana** [comment] 2016-09-25 01:49
Is the simulator you are connecting to running iOS 10? The tools that we use to connect to iOS for debugging need to be updated to work with iOS 10: https://github.com/google/ios-webkit-debug-proxy/issues/144

You could try updating them as mentioned in the linked issue: `brew update && brew upgrade libimobiledevice --HEAD && brew upgrade ios-webkit-debug-proxy`

**Comment by brusinow** [comment] 2016-09-25 02:05
That did it! Thanks for the quick and detailed response, these tools are a life saver.

**Comment by brusinow** [comment] 2016-10-04 18:05
I just got this same error on a different, pre-existing branch. Running the above updates didn't fix the problem. Any suggestions?

**Comment by MSLaguana** [comment] 2016-10-04 18:22
What do you mean by "pre-existing branch"? This is still you trying to deploy to the iOS simulator running iOS 10 correct?

Could you please try running it, and then on the command line running `curl localhost:9221/json` and `curl localhost:9223/json` (or whichever port number you get the ECONNREFUSED for)

**Comment by brusinow** [comment] 2016-10-04 18:38
Did a "cordova platform update ios" and somehow it fixed the problem. Sorry about that.

**Comment by letmaik** [comment] 2016-11-07 10:15
The proposed fixes don't work for me. Note that everything works fine when using UIWebView, even on iOS10 before applying the proposed fixes. Only when using WKWebView it doesn't work anymore. I can still connect to the simulator via the Safari debugging tools.

**Comment by StobyWan** [comment] 2017-10-04 22:48
@letmaik having same issue... were you able to resolve? pretty sure the problem is the local server WKWebview runs on unlike the standard UIWebview. would be cool to find a fix.

**Comment by iTOYS** [comment] 2018-05-11 12:43
Hi there, sorry for delay.
Are you still faced this issue?

**Comment by iTOYS** [comment] 2018-05-16 13:36
Closing now! Feel free to reopen if you still have this issue

**Closed by iTOYS** 2018-05-16 13:36 UTC
Labels: needrepro, triaged
