### ISSUE TITLE
Cannot run on emulator with ionicLiveReload: true

### ISSUE THREAD

**Issue by sertal70** [Microsoft/vscode-cordova#492] opened 2019-01-30 14:00 UTC
## Actual Behavior
When running the following configuration:
```
      "name": "Run android on emulator (livereload)",
      "type": "cordova",
      "request": "launch",
      "platform": "android",
      "target": "emulator-5554",
      "sourceMaps": true,
      "livereload": true,
      "ionicLiveReload": true,
      "devServerTimeout": 600000,
      "cwd": "${workspaceFolder}/src"
```

VSC shows the message: 

![image](https://user-images.githubusercontent.com/25665841/51985748-ecee8c80-249e-11e9-800c-e43a62717b62.png)

and the debug session doesn't start.

## Expected Behavior
VSC starts the debug session with ionic livereload option active.

## Software versions
- Cordova VS Code extension version: 1.7.0
- VSCode version: 1.30.2
- OS platform and version: macOS Mojave 10.14.2
- NodeJS version: v8.9.3
- Cordova version: 8.1.1
- Cordova-Android/iOS/Windows version: android 6.4.0, ios 4.5.5
- ionic (Ionic CLI): 4.5.0
- Ionic Framework: ionic-angular 3.9.2
- @ionic/app-scripts: 3.2.0

## Outputs (Include if relevant)
- Output of the Debug Console (View -> Toggle Debug Console):
```
Launching for android (This may take a while)...
Starting Ionic dev server (live reload: true)
The Ionic live reload server exited unexpectedly
```
- Output of the Cordova output channel (View -> Toggle Output -> Select Cordova in ListBox):
```
N/A
```
- Output of the Developer Tools console (Help -> Toggle Developer Tools -> Select Console tab):
```
N/A
```

**Comment by ruslan-bikkinin** [comment] 2019-01-31 11:50
Hi @sertal70 JFYI i was able to reproduce it on my side, so I'm digging into it right now.

**Comment by sertal70** [comment] 2019-01-31 17:19
Hi @ruslan-bikkinin , good to know! Let me know if I can help in some way.

**Comment by ruslan-bikkinin** [comment] 2019-02-01 09:07
@sertal70 Most likely ionic process is complaining about multiple network adapters found on your machine. The solution for this is to `run ionic cordova run android --livereload`, wait until prompt for choosing IP address is appeared, copy the one that fits, and add it to your debug configuration as `devServerAddress` parameter. We have this check in our code but for some reason it hasn't worked in your case. Please, try it and let us know if it works.

**Comment by CodeDoctor34** [comment] 2019-02-01 17:36
@ruslan-bikkinin I can confirm this seemed to fix things for me. However, with that said I had a lot of issues trying to get things to run right when I first set this up. Ultimately, I had to uninstall the extension altogether. Re-install, and then I had the "The Ionic live to reload server exited unexpectedly" error. I was using the "run arguments" to set my dev server address and live to reload. I found that I had to remove the run arguments and use the built-in properties in the config file for this to start working.

**Comment by CodeDoctor34** [comment] 2019-02-01 17:45
@ruslan-bikkinin Scratch that, spoke too soon. Looks like it worked because it never actually started the live reload server..... the following configuration is what I used and while it does start up and deploy to my device, the live reload is not running.
        {
            "name": "Run Android on device",
            "type": "cordova",
            "request": "launch",
            "platform": "android",
            "target": "device",
            "port": 9222,    
            "devServerTimeout": 200000,
            "livereload": true,
            "devServerAddress": "192.168.0.10",            
            "sourceMaps": true,
            "cwd": "${workspaceFolder}",                                  
        },

**Comment by sertal70** [comment] 2019-02-01 20:44
@ruslan-bikkinin actually my computer has two network interfaces, so I picked the right one and added it to the launch configuration in the `devServerAddress` parameter, then I started the debug session which showed a little bit of progress but then ended with the error:

![image](https://user-images.githubusercontent.com/25665841/52148528-45be5080-266a-11e9-8f1c-a9f1e33c1095.png)

Also the debug console shows these messages:

```
...
[app-scripts] [21:38:46]  build dev finished in 19.94 s 
[app-scripts] [21:38:46]  watch ready in 20.00 s 
[INFO] Development server running!
       
       Local: http://localhost:8100
       
       Use Ctrl+C to quit this process
Building and deploying app
Error in the Ionic live reload server:
Error: listen EADDRNOTAVAIL fe80::1:8100 at Object._errnoException (util.js:1024:11) at _exceptionWithHostPort (util.js:1046:20) at Server.setupListenHandle [as _listen2] (net.js:1334:19) at listenInCluster (net.js:1392:12) at doListen (net.js:1501:7) at _combinedTickCallback (internal/process/next_tick.js:141:11) at process._tickCallback (internal/process/next_tick.js:180:9) code: 'EADDRNOTAVAIL', errno: 'EADDRNOTAVAIL', syscall: 'listen', address: 'fe80::1', port: 8100 }
```

Hope this helps!

**Comment by hsusyh** [comment] 2019-02-01 21:15
I have the same issue when I try to **run iOS on device**
```
      "name": "Run iOS on device",
      "type": "cordova",
      "request": "launch",
      "platform": "ios",
      "target": "device",
      "port": 9220,
      "sourceMaps": true,
      "cwd": "${workspaceFolder}",
      "ionicLiveReload": true
```
got an error message `The Ionic live reload server exited unexpectedly`

**Comment by ruslan-bikkinin** [comment] 2019-02-03 09:45
Thanks for the feedback guys, looks like a bug to me. I am working on a fix now, so as soon I get more news I'll let you know.

**Comment by ruslan-bikkinin** [comment] 2019-02-04 15:46
@CodeDoctor34 could you please create separated issue with the description of your specific case because seems to be that your problem doesn't relate to this one.

**Comment by CodeDoctor34** [comment] 2019-02-04 18:20
@ruslan-bikkinin Sure, I have created a separate issue #495

**Comment by ruslan-bikkinin** [comment] 2019-02-14 12:38
Guys, v1.8.0 with fixes for livereload cases has just been released, so I'm closing this. Please feel free to create a new one if needed.

**Closed by ruslan-bikkinin** 2019-02-14 12:38 UTC
Labels: bug, fix-in-master, ionic
