### ISSUE TITLE
Attaching to app take long time before working

### ISSUE THREAD

**Issue by jpchenel** [microsoft/vscode-cordova#630] opened 2020-06-01 19:46 UTC
Recently, I can't use the debugger anymore for Cordova projects. It takes forever to attach to the app. When I write .scripts in the command windows, I saw scripts loading once at each 15-20 sec. or so. The breakpoints are greyed out and after 2 minutes 15 sec. they turn red.

With fresh dummy project (HelloWorld), it takes 8 sec. to load. If I add 16 dummy .js file, it takes 1 min. to load.

Exemple of dummy js file
```
var _app = (function () {
    var private = "";
    var public1 = function () {
        return '';
    };
    var public2 = function () {
        return '';
    };
    function private() {

    }
    return {
        public1: public1,
        public2: public2
    }
})();
```
launch.json
```
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Run android on device",
            "type": "cordova",
            "request": "launch",
            "platform": "android",
            "target": "device",
            "sourceMaps": true,
            "cwd": "${workspaceFolder}"
        }
    ]
}
```

I don't know if it is a circumstance, but before the last update of VS Code it was working. The last time I've played with this project was in the last month.

I've updated nodejs to last version. I've also tried VS Code 1.44.2 with no success.

Thanks for your help.

## Actual Behavior
1. Start debugging.
2. Wait 60 sec befor app is attached.

## Expected Behavior
1. Start debugging.
2. Wait few sec (1-5 sec) befor app is attached.

## Software versions
- Cordova VS Code extension version: 1.9.4
- VSCode version: 1.45.1 (user)
- OS platform and version: Windows 10
- NodeJS version: 12.17
- Cordova version: 9.0.0 (cordova-lib@9.0.1)
- Cordova-Android version: 8.1.0

## Outputs (Include if relevant)
- Output of the Debug Console (View -> Toggle Debug Console):
```
PASTE OUTPUT HERE
```
- Output of the Cordova output channel (View -> Toggle Output -> Select Cordova in ListBox):
```
PASTE OUTPUT HERE
```
- Output of the Developer Tools console (Help -> Toggle Developer Tools -> Select Console tab):
```
PASTE OUTPUT HERE
```

**Comment by SounD120** [comment] 2020-06-02 10:13
Hi @jpchenel , thanks for reaching us. I tried to reproduce this now, I created 10 dummy files with the code you described, added them to `index.html`, tried to build the app and couldn't see any difference in build time. Could you please send us a minimal demo app in which this behavior is reproduced, so we that we can investigate this case?

You can also try to reinstall the extension, but it is important to fully reopen the VS Code so you can follow this instruction:
* Remove extension
* Close VS Code
* Open VS Code
* Install the extension

Could you please also attach your build and debug logs as described below?
## Outputs
- Output of the Debug Console (View -> Toggle Debug Console):
```
PASTE OUTPUT HERE
```
- Output of the Cordova output channel (View -> Toggle Output -> Select Cordova in ListBox):
```
PASTE OUTPUT HERE
```
- Output of the Developer Tools console (Help -> Toggle Developer Tools -> Select Console tab):
```
PASTE OUTPUT HERE
```

**Comment by jpchenel** [comment] 2020-06-02 13:42
Thank for followup.
Here are some details.

[hello.zip](https://github.com/microsoft/vscode-cordova/files/4717423/hello.zip)

I've included a video that show the time between the "Attaching to app." event and the attachement itself.

[attaching to app.zip](https://github.com/microsoft/vscode-cordova/files/4717489/attaching.to.app.zip)

## Outputs (Include if relevant)
- Output of the Debug Console (View -> Toggle Debug Console):
```
Launching for android (This may take a while)...
No scripts found for hook "before_run".
No scripts found for hook "before_prepare".
Checking config.xml and package.json for saved platforms that haven't been added to the project
Config.xml and package.json platforms are the same. No pkg.json modification.
Package.json and config.xml platforms are different. Updating config.xml with most current list of platforms.
PlatformApi successfully found for platform android
Checking for saved plugins that haven't been added to the project
Checking for any plugins added to the project that have not been installed in android platform
No differences found between plugins added to project and installed in android platform. Continuing...
Generating platform-specific config.xml from defaults for android at C:\Temp\cordova\hello\platforms\android\app\src\main\res\xml\config.xml
Merging project's config.xml into platform-specific android config.xml
[Gradle Properties] Preparing Configuration
[Gradle Properties] Appending default configuration properties
[Gradle Properties] Appending custom configuration properties
[Gradle Properties] Updating and Saving File
Merging and updating files from [www, platforms\android\platform_www] to platforms\android\app\src\main\assets\www
  copy  platforms\android\platform_www\cordova-js-src\android\nativeapiprovider.js platforms\android\app\src\main\assets\www\cordova-js-src\android\nativeapiprovider.js (updated file)
  copy  platforms\android\platform_www\cordova-js-src\android\promptbasednativeapi.js platforms\android\app\src\main\assets\www\cordova-js-src\android\promptbasednativeapi.js (updated file)
  copy  platforms\android\platform_www\cordova-js-src\exec.js platforms\android\app\src\main\assets\www\cordova-js-src\exec.js (updated file)
  copy  platforms\android\platform_www\cordova-js-src\platform.js platforms\android\app\src\main\assets\www\cordova-js-src\platform.js (updated file)
  copy  platforms\android\platform_www\cordova-js-src\plugin\android\app.js platforms\android\app\src\main\assets\www\cordova-js-src\plugin\android\app.js (updated file)
  copy  platforms\android\platform_www\cordova.js platforms\android\app\src\main\assets\www\cordova.js (updated file)
  copy  platforms\android\platform_www\cordova_plugins.js platforms\android\app\src\main\assets\www\cordova_plugins.js (updated file)
  copy  www\css\index.css platforms\android\app\src\main\assets\www\css\index.css (updated file)
  copy  www\index.html platforms\android\app\src\main\assets\www\index.html (updated file)
  copy  www\js\1 (1).js platforms\android\app\src\main\assets\www\js\1 (1).js (updated file)
  copy  www\js\1 (2).js platforms\android\app\src\main\assets\www\js\1 (2).js (updated file)
  copy  www\js\1 (3).js platforms\android\app\src\main\assets\www\js\1 (3).js (updated file)
  copy  www\js\1 (4).js platforms\android\app\src\main\assets\www\js\1 (4).js (updated file)
  copy  www\js\1 (5).js platforms\android\app\src\main\assets\www\js\1 (5).js (updated file)
  copy  www\js\1 (6).js platforms\android\app\src\main\assets\www\js\1 (6).js (updated file)
  copy  www\js\1 (7).js platforms\android\app\src\main\assets\www\js\1 (7).js (updated file)
  copy  www\js\1 (8).js platforms\android\app\src\main\assets\www\js\1 (8).js (updated file)
  copy  www\js\2 (1).js platforms\android\app\src\main\assets\www\js\2 (1).js (updated file)
  copy  www\js\2 (2).js platforms\android\app\src\main\assets\www\js\2 (2).js (updated file)
  copy  www\js\2 (3).js platforms\android\app\src\main\assets\www\js\2 (3).js (updated file)
  copy  www\js\2 (4).js platforms\android\app\src\main\assets\www\js\2 (4).js (updated file)
  copy  www\js\2 (5).js platforms\android\app\src\main\assets\www\js\2 (5).js (updated file)
  copy  www\js\2 (6).js platforms\android\app\src\main\assets\www\js\2 (6).js (updated file)
  copy  www\js\2 (7).js platforms\android\app\src\main\assets\www\js\2 (7).js (updated file)
  copy  www\js\2 (8).js platforms\android\app\src\main\assets\www\js\2 (8).js (updated file)
  copy  www\js\index.js platforms\android\app\src\main\assets\www\js\index.js (updated file)
Wrote out android application name "HelloWorld" to C:\Temp\cordova\hello\platforms\android\app\src\main\res\values\strings.xml
android-versionCode not found in config.xml. Generating a code based on version in config.xml (1.0.0): 10000
Wrote out Android package name "com.exemple.hello" to C:\Temp\cordova\hello\platforms\android\app\src\main\java\com\exemple\hello\MainActivity.java
This app does not have launcher icons defined
This app does not have splash screens defined
This app does not have additional resource files defined
Prepared android project successfully
No scripts found for hook "after_prepare".
Checking Java JDK and Android SDK versions
ANDROID_SDK_ROOT=undefined (recommended setting)
ANDROID_HOME=C:\Users\jp.chenel\AppData\Local\Android\Sdk (DEPRECATED)
Subproject Path: CordovaLib
Subproject Path: app
Running command: C:\Temp\cordova\hello\platforms\android\gradlew cdvBuildDebug -b C:\Temp\cordova\hello\platforms\android\build.gradle
> Task :app:preBuild UP-TO-DATE
> Task :CordovaLib:preBuild UP-TO-DATE
> Task :CordovaLib:preDebugBuild UP-TO-DATE
> Task :CordovaLib:checkDebugManifest UP-TO-DATE
> Task :CordovaLib:processDebugManifest UP-TO-DATE
> Task :app:preDebugBuild UP-TO-DATE
> Task :CordovaLib:compileDebugAidl NO-SOURCE
> Task :app:compileDebugAidl NO-SOURCE
> Task :CordovaLib:packageDebugRenderscript NO-SOURCE
> Task :app:compileDebugRenderscript UP-TO-DATE
> Task :app:checkDebugManifest UP-TO-DATE
> Task :app:generateDebugBuildConfig UP-TO-DATE
> Task :app:prepareLintJar UP-TO-DATE
> Task :app:generateDebugSources UP-TO-DATE
> Task :CordovaLib:compileDebugRenderscript UP-TO-DATE
> Task :CordovaLib:generateDebugBuildConfig UP-TO-DATE
> Task :CordovaLib:generateDebugResValues UP-TO-DATE
> Task :CordovaLib:generateDebugResources UP-TO-DATE
> Task :CordovaLib:packageDebugResources UP-TO-DATE
> Task :CordovaLib:generateDebugRFile UP-TO-DATE
> Task :CordovaLib:prepareLintJar UP-TO-DATE
> Task :CordovaLib:generateDebugSources UP-TO-DATE
> Task :CordovaLib:javaPreCompileDebug UP-TO-DATE
> Task :CordovaLib:compileDebugJavaWithJavac UP-TO-DATE
> Task :CordovaLib:processDebugJavaRes NO-SOURCE
> Task :CordovaLib:transformClassesAndResourcesWithPrepareIntermediateJarsForDebug UP-TO-DATE
> Task :app:javaPreCompileDebug UP-TO-DATE
> Task :app:mainApkListPersistenceDebug UP-TO-DATE
> Task :app:generateDebugResValues UP-TO-DATE
> Task :app:generateDebugResources UP-TO-DATE
> Task :app:mergeDebugResources UP-TO-DATE
> Task :app:createDebugCompatibleScreenManifests UP-TO-DATE
> Task :app:processDebugManifest UP-TO-DATE
> Task :app:processDebugResources UP-TO-DATE
> Task :app:compileDebugJavaWithJavac UP-TO-DATE
> Task :app:compileDebugNdk NO-SOURCE
> Task :app:compileDebugSources UP-TO-DATE
> Task :app:mergeDebugShaders UP-TO-DATE
> Task :app:compileDebugShaders UP-TO-DATE
> Task :app:generateDebugAssets UP-TO-DATE
> Task :CordovaLib:mergeDebugShaders UP-TO-DATE
> Task :CordovaLib:compileDebugShaders UP-TO-DATE
> Task :CordovaLib:generateDebugAssets UP-TO-DATE
> Task :CordovaLib:packageDebugAssets UP-TO-DATE
> Task :app:mergeDebugAssets UP-TO-DATE
> Task :app:validateSigningDebug UP-TO-DATE
> Task :app:signingConfigWriterDebug UP-TO-DATE
> Task :app:transformClassesWithDexBuilderForDebug UP-TO-DATE
> Task :app:transformDexArchiveWithExternalLibsDexMergerForDebug UP-TO-DATE
> Task :app:transformDexArchiveWithDexMergerForDebug UP-TO-DATE
> Task :app:mergeDebugJniLibFolders UP-TO-DATE
> Task :CordovaLib:compileDebugNdk NO-SOURCE
> Task :CordovaLib:mergeDebugJniLibFolders UP-TO-DATE
> Task :CordovaLib:transformNativeLibsWithMergeJniLibsForDebug UP-TO-DATE
> Task :CordovaLib:transformNativeLibsWithIntermediateJniLibsForDebug UP-TO-DATE
> Task :app:transformNativeLibsWithMergeJniLibsForDebug UP-TO-DATE
> Task :app:processDebugJavaRes NO-SOURCE
> Task :app:transformResourcesWithMergeJavaResForDebug UP-TO-DATE
> Task :app:packageDebug UP-TO-DATE
> Task :app:assembleDebug UP-TO-DATE
> Task :app:cdvBuildDebug UP-TO-DATE

BUILD SUCCESSFUL in 3s
42 actionable tasks: 42 up-to-date
Command finished with error code 0: C:\Temp\cordova\hello\platforms\android\gradlew cdvBuildDebug,-b,C:\Temp\cordova\hello\platforms\android\build.gradle
Built the following apk(s): 
	C:\Temp\cordova\hello\platforms\android\app\build\outputs\apk\debug\app-debug.apk
No scripts found for hook "before_deploy".
Checking Java JDK and Android SDK versions
ANDROID_SDK_ROOT=undefined (recommended setting)
ANDROID_HOME=C:\Users\jp.chenel\AppData\Local\Android\Sdk (DEPRECATED)

Command finished with error code 0: adb devices
Running adb shell command "cat /proc/cpuinfo" on target 42007c95ac0c15f7...Command finished with error code 0: adb -s,42007c95ac0c15f7,shell,cat,/proc/cpuinfo
Using apk: C:\Temp\cordova\hello\platforms\android\app\build\outputs\apk\debug\app-debug.apk
Package name: com.exemple.hello
Installing apk C:\Temp\cordova\hello\platforms\android\app\build\outputs\apk\debug\app-debug.apk on target 42007c95ac0c15f7...Command finished with error code 0: adb -s,42007c95ac0c15f7,install,-r,C:\Temp\cordova\hello\platforms\android\app\build\outputs\apk\debug\app-debug.apk
Running adb shell command "input keyevent 82" on target 42007c95ac0c15f7...
Command finished with error code 0: adb -s,42007c95ac0c15f7,shell,input,keyevent,82
Starting application "com.exemple.hello/.MainActivity" on target 42007c95ac0c15f7...
Running adb shell command "am start -W -a android.intent.action.MAIN -ncom.exemple.hello/.MainActivity" on target 42007c95ac0c15f7...

Command finished with error code 0: adb -s,42007c95ac0c15f7,shell,am,start,-W,-a,android.intent.action.MAIN,-ncom.exemple.hello/.MainActivity
LAUNCH SUCCESS
No scripts found for hook "after_run".
App successfully launched
Attaching to android
Forwarding debug port
Attaching to app.

Received Event: deviceready
```
- Output of the Cordova output channel (View -> Toggle Output -> Select Cordova in ListBox):
```
########### EXECUTING: cordova.cmd build android ###########
Checking Java JDK and Android SDK versions
ANDROID_SDK_ROOT=undefined (recommended setting)
ANDROID_HOME=C:\Users\jp.chenel\AppData\Local\Android\Sdk (DEPRECATED)
Subproject Path: CordovaLib
Subproject Path: app
> Task :app:preBuild UP-TO-DATE
> Task :CordovaLib:preBuild UP-TO-DATE
> Task :CordovaLib:preDebugBuild UP-TO-DATE
> Task :CordovaLib:checkDebugManifest UP-TO-DATE
> Task :CordovaLib:processDebugManifest UP-TO-DATE
> Task :app:preDebugBuild UP-TO-DATE
> Task :CordovaLib:compileDebugAidl NO-SOURCE
> Task :app:compileDebugAidl NO-SOURCE
> Task :CordovaLib:packageDebugRenderscript NO-SOURCE
> Task :app:compileDebugRenderscript UP-TO-DATE
> Task :app:checkDebugManifest UP-TO-DATE
> Task :app:generateDebugBuildConfig UP-TO-DATE
> Task :app:prepareLintJar UP-TO-DATE
> Task :app:generateDebugSources UP-TO-DATE
> Task :CordovaLib:compileDebugRenderscript UP-TO-DATE
> Task :CordovaLib:generateDebugBuildConfig UP-TO-DATE
> Task :CordovaLib:generateDebugResValues UP-TO-DATE
> Task :CordovaLib:generateDebugResources UP-TO-DATE
> Task :CordovaLib:packageDebugResources UP-TO-DATE
> Task :CordovaLib:generateDebugRFile UP-TO-DATE
> Task :CordovaLib:prepareLintJar UP-TO-DATE
> Task :CordovaLib:generateDebugSources UP-TO-DATE
> Task :CordovaLib:javaPreCompileDebug UP-TO-DATE
> Task :CordovaLib:compileDebugJavaWithJavac UP-TO-DATE
> Task :CordovaLib:processDebugJavaRes NO-SOURCE
> Task :CordovaLib:transformClassesAndResourcesWithPrepareIntermediateJarsForDebug UP-TO-DATE
> Task :app:javaPreCompileDebug UP-TO-DATE
> Task :app:mainApkListPersistenceDebug UP-TO-DATE
> Task :app:generateDebugResValues UP-TO-DATE
> Task :app:generateDebugResources UP-TO-DATE
> Task :app:mergeDebugResources UP-TO-DATE
> Task :app:createDebugCompatibleScreenManifests UP-TO-DATE
> Task :app:processDebugManifest UP-TO-DATE
> Task :app:processDebugResources UP-TO-DATE
> Task :app:compileDebugJavaWithJavac UP-TO-DATE
> Task :app:compileDebugNdk NO-SOURCE
> Task :app:compileDebugSources UP-TO-DATE
> Task :app:mergeDebugShaders UP-TO-DATE
> Task :app:compileDebugShaders UP-TO-DATE
> Task :app:generateDebugAssets UP-TO-DATE
> Task :CordovaLib:mergeDebugShaders UP-TO-DATE
> Task :CordovaLib:compileDebugShaders UP-TO-DATE
> Task :CordovaLib:generateDebugAssets UP-TO-DATE
> Task :CordovaLib:packageDebugAssets UP-TO-DATE
> Task :app:mergeDebugAssets UP-TO-DATE
> Task :app:validateSigningDebug UP-TO-DATE
> Task :app:signingConfigWriterDebug UP-TO-DATE
> Task :app:transformClassesWithDexBuilderForDebug UP-TO-DATE
> Task :app:transformDexArchiveWithExternalLibsDexMergerForDebug UP-TO-DATE
> Task :app:transformDexArchiveWithDexMergerForDebug UP-TO-DATE
> Task :app:mergeDebugJniLibFolders UP-TO-DATE
> Task :CordovaLib:compileDebugNdk NO-SOURCE
> Task :CordovaLib:mergeDebugJniLibFolders UP-TO-DATE
> Task :CordovaLib:transformNativeLibsWithMergeJniLibsForDebug UP-TO-DATE
> Task :CordovaLib:transformNativeLibsWithIntermediateJniLibsForDebug UP-TO-DATE
> Task :app:transformNativeLibsWithMergeJniLibsForDebug UP-TO-DATE
> Task :app:processDebugJavaRes NO-SOURCE
> Task :app:transformResourcesWithMergeJavaResForDebug UP-TO-DATE
> Task :app:packageDebug UP-TO-DATE
> Task :app:assembleDebug UP-TO-DATE
> Task :app:cdvBuildDebug UP-TO-DATE

BUILD SUCCESSFUL in 2s
42 actionable tasks: 42 up-to-date
Built the following apk(s): 
	c:\Temp\cordova\hello\platforms\android\app\build\outputs\apk\debug\app-debug.apk
########### FINISHED EXECUTING: cordova.cmd build android ###########

```
- Output of the Developer Tools console (Help -> Toggle Developer Tools -> Select Console tab):
```
[Extension Host] detect tortoiseSVNProcExePath
console.ts:137 [Extension Host] Git installation not found.
t.log @ console.ts:137
console.ts:137 [Extension Host] rejected promise not handled within 1 second: true
t.log @ console.ts:137
log.ts:197   ERR An unknown error occurred. Please consult the log for more details.
2console.ts:137 [Extension Host] (node:11752) [DEP0022] DeprecationWarning: os.tmpDir() is deprecated. Use os.tmpdir() instead.
```

**Comment by JiglioNero** [comment] 2020-06-03 13:22
Hello @jpchenel , we tried to reproduce your script, but we have attach occurs within 2-6 seconds. Please try to restart the system and / or get rid of all extraneous processes and try again. If the problem remains, please run `npx envinfo` and send us the result.

**Comment by jpchenel** [comment] 2020-06-04 00:42
Thank for followup.

I've killed all know process that was running in background and started the debugging. Same things.

Here is the output command.

```
  System:
    OS: Windows 10 10.0.18363
    CPU: (4) x64 Intel(R) Core(TM) i5-7200U CPU @ 2.50GHz
    Memory: 2.10 GB / 7.91 GB
  Binaries:
    Node: 12.17.0 - C:\Program Files\nodejs\node.EXE     
    npm: 6.14.4 - C:\Program Files\nodejs\npm.CMD        
  Managers:
    Gradle: 6.3 - C:\Gradle\gradle-6.3\bin\gradle.BAT
  IDEs:
    Android Studio: Version  3.6.0.0 AI-192.7142.36.36.6308749
    VSCode: 1.45.1 - C:\Users\jp.chenel\AppData\Local\Programs\Microsoft VS Code\bin\code.CMD
  Languages:
    Java: 1.8.0_241 - C:\Program Files\Java\jdk1.8.0_241\bin\javac.EXE
    PHP: 7.2.30 - C:\PHP\php.EXE
    Python: 2.7.1 - C:\csvn\Python25\python.EXE
  Databases:
    SQLite: 3.28.0 - C:\Users\jp.chenel\AppData\Local\Android\Sdk\platform-tools\sqlite3.EXE
  Browsers:
    Edge: 44.18362.449.0
    Internet Explorer: 11.0.18362.1
```

With best regards,

**Comment by JiglioNero** [comment] 2020-06-05 09:10
@jpchenel, with the same configurations as yours, we couldn’t reproduce the same problem. The reason may be that your node settings are different from the default settings. Please try resetting the npm configuration:
For user settings:
`echo ""> $ (npm config get userconfig)`
For global settings:
`echo ""> $ (npm config get globalconfig)`
Also make sure developer settings are configured correctly on your device: enable `Developer options`, then enable `USB debugging`, `Install via USB`, `USB debugging`, `Wait for debugger` in Debugging section.
Incorrect settings for `Developer options` may cause unexpected errors like this https://github.com/microsoft/vscode-cordova/issues/587.

**Comment by jpchenel** [comment] 2020-06-08 17:19
@JiglioNero, I've tried all the settings, but none of them make it work.
I've configured a new virtual environment (vmware) for testing it and it works!
I don’t know the source of this problem.
I'll continue to debug on the virtual environment.

Thanks for your help.

**Comment by JiglioNero** [comment] 2020-06-09 08:40
We are glad that your problem has been resolved. In this case, I close this issue.

**Closed by JiglioNero** 2020-06-09 08:40 UTC
Labels: resolved
