### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by BMO-crypto** [microsoft/vscode-cordova#637] opened 2020-07-14 17:54 UTC
- Issue Type: `Performance`
- Extension Name: `cordova-tools`
- Extension Version: `1.9.4`
- OS Version: `Windows_NT x64 10.0.18362`
- VSCode version: `1.47.1`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`C:\Users\pl-brandon.moulden\msjsdiag.cordova-tools-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load

**Comment by SounD120** [comment] 2020-07-15 08:39
Looks like duplicate of #517

**Closed by SounD120** 2020-07-15 08:39 UTC
Labels: duplicate, performance
