### ISSUE TITLE
Unable to get device OS version

### ISSUE THREAD

**Issue by jQrgen** [Microsoft/vscode-cordova#353] opened 2017-12-12 17:42 UTC
Hey,

I get the following error when attempting to "Run iOS on device":
```js
** EXPORT SUCCEEDED **
Installing app on device
Launching app
Unable to get device OS version
```

Following is my config, i tried setting "appStepLaunchTimeout": 60000 but it did not seem to work
```json
{
    "version": "0.2.0",
    "configurations": [
        {
            "runArguments": ["--consolelogs", "--buildConfig=build.json"],
            "name": "Run iOS on device",
            "type": "cordova",
            "request": "launch",
            "platform": "ios",
            "target": "device",
            "port": 9220,
            "sourceMaps": true,
            "cwd": "${workspaceRoot}",
            "ionicLiveReload": true,
            "appStepLaunchTimeout": 60000
        }
     ]
}
```

**Comment by iTOYS** [comment] 2017-12-29 10:18
Hi @jQrgen 
Thanks for reporting!
Could you please run `ideviceinfo -s -k ProductVersion` in your terminal and paste output here

**Comment by sergey-akhalkov** [comment] 2018-01-31 16:28
Hi @jQrgen, just a friendly ping, could you please let us know if the issue still has place for you and if you have a chance to take a look at the message above?

**Comment by jQrgen** [comment] 2018-01-31 20:56
The issue still persists.

@iTOYS Here are the results from the command you posted:
```
$ ideviceinfo -s -k ProductVersion
11.2.5
```

Thanks

**Comment by annakocheshkova** [comment] 2018-02-21 10:58
Hi @jQrgen, we have started investigating your issue. It seems that issue can be connected with your device. 

To see what's the problem, could you please modify the code of the `src\debugger\cordovaIosDeviceLauncher` > `getDiskImage` and replace the `catch` block with the following: 
```
.catch(function(e): string {
   throw new Error('Unable to get device OS version: ' + e.message); 
});
```

Then paste the actual error here.
You can do that simply by downloading the extension from the repo, modifying the lines, then launching it, opening your project and doing the same repro steps.
Thank you for the assistance!

**Comment by annakocheshkova** [comment] 2018-02-21 12:58
Hi @jQrgen, we have started investigating your issue, but can't reproduce it. It seems that issue can be connected with your device. 

To see what's the problem, could you please download extension from the [following ](https://github.com/annakocheshkova/vscode-cordova/tree/error_info_fix) branch, launch it, open your project and try to reproduce the issue, then paste the actual error here.
Thank you for the assistance!

**Comment by annakocheshkova** [comment] 2018-02-26 11:29
Hi @jQrgen, do you have any updates? Does the issue still persist for you?

**Comment by max-mironov** [comment] 2018-03-05 10:59
Closing this at the meantime, please let us know when you get a chance to revisit this issue.

**Closed by max-mironov** 2018-03-05 10:59 UTC
Labels: need-more-info, needrepro
