### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by jing-zhou** [microsoft/vscode-cordova#567] opened 2019-09-09 01:22 UTC
[msjsdiag.cordova-tools-unresponsive.cpuprofile.txt](https://github.com/microsoft/vscode-cordova/files/3588318/msjsdiag.cordova-tools-unresponsive.cpuprofile.txt)
- Issue Type: `Performance`
- Extension Name: `cordova-tools`
- Extension Version: `1.8.5`
- OS Version: `Linux x64 5.0.0-27-generic`
- VSCode version: `1.38.0`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`/home/wjz/msjsdiag.cordova-tools-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/Microsoft/vscode/wiki/Explain:-extension-causes-high-cpu-load
[msjsdiag.cordova-tools-unresponsive.cpuprofile.txt](https://github.com/microsoft/vscode-cordova/files/3588323/msjsdiag.cordova-tools-unresponsive.cpuprofile.txt)

**Comment by SounD120** [comment] 2019-09-17 14:25
Hi @jing-zhou . As seen from your cpu profile extension activation caused the high cpu load. Do you remember what did you do in VS Code when this message showed up?

**Comment by SounD120** [comment] 2019-09-24 06:34
Hi @jing-zhou . Do you have a chance to look at this?

**Comment by SounD120** [comment] 2019-09-25 07:46
@jing-zhou Since the high cpu load caused by the extension activation and there are no other details, I am closing this issue because it is duplicating #517. Thanks.

**Closed by SounD120** 2019-09-25 07:46 UTC
Labels: duplicate, performance
