### ISSUE TITLE
Simulate in browser not working correctly

### ISSUE THREAD

**Issue by RDeluxe** [Microsoft/vscode-cordova#259] opened 2017-03-13 06:53 UTC
It usually works well the first time after adding a platform, but after stopping/restarting the simulation the **onDeviceReady** event will never fire.

I tested directly cordova-simulate and it does not have this problem, so I suppose this is related to this plugin directly, one way or another.

**Comment by vladimir-kotikov** [comment] 2017-03-13 08:53
@RDeluxe, thanks for reporting! Could you please add more details: your OS,  VSCode, NodeJS versions. Also are you trying to simulate Ionic1/Ionic2 or Cordova app? What's the debug console output in case of error?

**Comment by matrosov-nikita** [comment] 2017-03-16 10:14
@RDeluxe, I was able to reproduce this bug with Ionic2 `tabs` template.

In my case logs from debug console look like:

    Launching for android (This may take a while)...
    Attaching to app
    Angular is running in the development mode. Call enableProdMode() to enable the production mode.
    deviceready has not fired after 5 seconds.
    Channel not fired: onNativeReady
    Channel not fired: onCordovaReady
    Channel not fired: onCordovaSimulateReady
    Native: deviceready did not fire within 5000ms. This can happen when plugins are in an inconsistent state. Try removing plugins from plugins/ and reinstalling them.

Uncaught exceptions in `polyfill.js` which make debugger to stop might be the cause of this problem (see [comment](https://github.com/Microsoft/vscode-cordova/issues/251#issuecomment-286037683) which explains this issue). There is workaround - to uncheck option `Uncaught exceptions` in breakpoints section. After this `deviceready` should be fired:

    Launching for android (This may take a while)...
    Attaching to app
    Angular is running in the development mode. Call enableProdMode() to enable the production mode.
    DEVICE READY FIRED AFTER 900 ms

Could you please check whether this workaround works for you?

**Comment by vladimir-kotikov** [comment] 2017-03-28 08:05
Closing this one. @RDeluxe, feel free to reopen if you're still experiencing any problems w/ simulation

**Closed by vladimir-kotikov** 2017-03-28 08:05 UTC
Labels: bug, external-report, need-more-info, needrepro, priority-medium, triaged

**Comment by RDeluxe** [comment] 2017-04-18 06:03
Hi,

Coming back to this. With vanilla Cordova (not Ionic) I get the same issue. Unchecking `Uncaught exceptions` did not help.

![code - insiders_2017-04-18_08-01-30](https://cloud.githubusercontent.com/assets/2767681/25116487/51570eca-240d-11e7-9dbc-3d48ac9b3f3a.png)
