### ISSUE TITLE
attach to running andoid on device  not breaking at the breakpoint

### ISSUE THREAD

**Issue by navs007** [microsoft/vscode-cordova#587] opened 2019-11-07 19:33 UTC
I am trying to hit the breakpoint on visual studio code on a .ts file ,
 but never hits it.
when i put a hard breakpoint using debugger chrome://inspect breaks.
The day i installed Cordova Tools it worked randomly but now totally not hitting the breakpoint.
 {
            "name": "Attach to running android on device",
            "type": "cordova",
            "request": "attach",
            "platform": "android",
            "target": "device",
            "port": 9222,
            "sourceMaps": true,
            "cwd": "${workspaceFolder}"
        },
{
            "name": "Attach to running android on emulator",
            "type": "cordova",
            "request": "attach",
            "platform": "android",
            "target": "emulator",
            "port": 9222,
            "sourceMaps": true,
            "cwd": "${workspaceFolder}"
        },

## Expected Behavior
hot the breakpoint

## Software versions
- Cordova VS Code extension version:
- VSCode version:
- OS platform and version:
- NodeJS version:
- Cordova version:
- Cordova-Android/iOS/Windows version:

## Outputs (Include if relevant)
- Output of the Debug Console (View -> Toggle Debug Console):
Attaching to android
Forwarding debug port
Attaching to app.

**Comment by RedMickey** [comment] 2019-11-08 07:19
Hi @navs007 and thanks for reaching us. Could you please send us a screenshot or code example with breakpoints which aren't caught by the debugger? It will help us reproduce this problem and investigate it faster. Thanks.

**Comment by navs007** [comment] 2019-11-08 19:14
![image](https://user-images.githubusercontent.com/57499616/68503791-b87bde00-0231-11ea-893d-0848b61abe48.png)


see line 1401 the debuggers breaks always in chrome://inspect
see line 1402/1401 does not break in visual studio code

**Comment by RedMickey** [comment] 2019-11-11 08:45
@navs007, could you please fill all fields in issue description according to the [issue template](https://github.com/microsoft/vscode-cordova/blob/master/.github/ISSUE_TEMPLATE.md)? Could you please also tell us your action sequence to reproduce issue behavior? It isn't so clear what `layerClick` function do and where it is called, there is just a guess from our side that this function is click handler. So we tried to reproduce such behavior, but didn't face any problems.

**Comment by RedMickey** [comment] 2019-11-14 13:30
@navs007, do you have a chance to look at this?

**Comment by navs007** [comment] 2019-11-14 14:14
Hi Yes its any code dosnt have to be button click.
its not debugging any of the break points.

How ever LayerClicked is an event emitter

@Output() public layerClicked: EventEmitter<object> = new EventEmitter<object>();

 <d-map (layerClicked)="SomeGeometry($event)">

Method Call
 this.layerClick(e, feature, layer, mapLayer);

Method declared
public layerClick(clickEvent: MouseEvent, feature: any, layer: any, mapLayer: MappingLayer): void {
debug point here      
  this.layerClicked.emit({ 'clickEvent': clickEvent, 'feature': feature, 'layer': layer, 'mapLayer': mapLayer });

        if ((this.multiselectMode === true || this.selectedMarkers.length === 0) && ((this.activeLayer != null && this.activeLayer.Id === mapLayer.Id) || mapLayer.LayerType === 'LocationReferences')) {

**Comment by RedMickey** [comment] 2019-11-15 07:58
@navs007, we tried to reproduce event emitter behavior the following way:

* Created a parent Angular component and added a child component in it
* Added `EventEmitter` in the child component
* Subscribed on that `EventEmitter` in the parent component
* Tried to debug these components

But we didn’t face any problem while executing debugging.
Could you please provide us a demo application in which that behavior is reproduced and an instruction about how to reproduce this issue?

**Comment by RedMickey** [comment] 2019-11-20 12:46
Hey @navs007, just a friendly ping on this.

**Comment by RedMickey** [comment] 2019-11-25 10:17
Hi @navs007. Unfortunately, we can't do much without a demo application reproducing that behavior, because the information from this app might be crucial for understanding why breakpoints aren't captured. If you face this issue again, please, provide us a demo.

**Comment by navs007** [comment] 2019-11-25 12:45
Hi How would you like the demo..you could add me on teams and i can show you the demo..Please send me your emailid so i can send you the info.If you need a different mode of demo let me know.

I will be happy to provide you the inpo to get it work

**Comment by RedMickey** [comment] 2019-11-25 13:06
@navs007, could you please send me a demo to this email v-miezhe@microsoft.com. Please attach an instruction to your demo which contains the steps describing what needs to be done to reproduce this problem and the exact positions of not working breakpoints in the code.

**Comment by navs007** [comment] 2019-11-25 13:56
I have sent you a mail with some info and attachment.
But in the mean while, please send me a sample code on which the mobile app is breaking on the breakpoints for you.

I want to know if its my project or all of them on my sys.

**Comment by RedMickey** [comment] 2019-11-27 09:11
@navs007, thanks for your demo, but it seems to be just a part of some other project. So we cannot create a test project because of lack of some dependencies. Please send the fully configured minimal demo application next time.
We created our demo application, checked whether breakpoints were captured and didn't face any problems while its debugging. The application sources are available in [demo-ionic repo](https://github.com/RedMickey/demo-ionic).
Could you please download it and try to debug using the instruction below?
1. Clone the [demo-ionic repo](https://github.com/RedMickey/demo-ionic) and install dependencies using the following commands:
    ```
    git clone https://github.com/RedMickey/demo-ionic.git
    cd demo-ionic
    npm i
    ```
1. Add Android platform to the project
    ```
    ionic cordova platform add android
    ```
1. Open the project in VS Code and create default `launch.json` file
    1 Click on gear icon
    2 Select Cordova
1. Set breakpoints in the following files:
    * projectRoot/src/app/tab1/parent-test-component/child-test-component/child-test-component.component.ts - set a breakpoint on the line 20 ![Screen Shot 2019-11-27 at 11 57 14](https://user-images.githubusercontent.com/33267199/69709110-e310d680-110d-11ea-8963-e34fdf2b673f.png)
    * projectRoot/src/app/tab1/parent-test-component/parent-test-component.component.ts - set a breakpoint on the line 15 ![Screen Shot 2019-11-27 at 11 57 47](https://user-images.githubusercontent.com/33267199/69709259-23705480-110e-11ea-8caa-19e20cf1b067.png)
1. Launch `Run Android on emulator` debug scenario
1. When the application starts, click on the `Click child component` button

After that the application should stop on the breakpoints.
Please let us know about your results.

**Comment by navs007** [comment] 2019-11-27 13:30
Thanks for the input.
However I tried launching  Android on Emulator following along through the steps...
I have the environment variables set up too...

I see nothing on the Emulator its been almost 5 min now..Attached is the screen shot for the same..
[RunAndroidOnEmulator.zip](https://github.com/microsoft/vscode-cordova/files/3897017/RunAndroidOnEmulator.zip)

**Comment by navs007** [comment] 2019-11-27 15:51
Some more inputs further to the above.
Other thing would be i run in the terminal with this command always to free  the memory and run app if not it breaks too. When i run with the below command it always runs on emulator and device

max-old-space-size=8192; ionic cordova run android -lcs

but on debug mode "Run Android on device/Emulator" how do i specify that max-old-space-size=8192

I updated the android studio/sdk -- not debugging
I connected to the Android Tab -- not debugging
I Made sure its running on same wifi -- not debugging

This is something I noticed, when i attach the "Run Android on Device" the application debugs occasionally and crashes suddenly and after it wont debug...

**Comment by RedMickey** [comment] 2019-11-28 07:17
@navs007, could you please fill the template below with logs from VS Code on trying to debug the demo application?  Could you please also send us outputs of the `ionic cordova run android -lcs` command when you are trying attach to the debugger?
## Outputs
- Output of the Debug Console (View -> Toggle Debug Console):
```
PASTE OUTPUT HERE
```
- Output of the Debug Console (View -> Toggle Debug Console -> Select `Attach to running android on device` or `Attach to running android on emulator` in ListBox):
```
PASTE OUTPUT HERE
```
- Output of the Cordova output channel (View -> Toggle Output -> Select Cordova in ListBox):
```
PASTE OUTPUT HERE
```
- Output of the Developer Tools console (Help -> Toggle Developer Tools -> Select Console tab):
```
PASTE OUTPUT HERE
```

**Comment by navs007** [comment] 2019-11-28 14:47
**This Section Of the Log Is only Related to My Actual App**
** Below Throws and error**
**Not The Demo App but My App

Debug Console when Run Android On Emulator ie debug mode** 

[ng] Thu, 28 Nov 2019 14:21:11 GMT express:router:layer new '/'
[ng] Thu, 28 Nov 2019 14:21:11 GMT express:router:route rebind '*'
[ng] Thu, 28 Nov 2019 14:21:11 GMT express:router:layer new '/'
[ng] Thu, 28 Nov 2019 14:21:11 GMT express:router:route report '*'
[ng] Thu, 28 Nov 2019 14:21:11 GMT express:router:layer new '/'
[ng] Thu, 28 Nov 2019 14:21:11 GMT express:router:route search '*'
[ng] Thu, 28 Nov 2019 14:21:11 GMT express:router:layer new '/'
[ng] Thu, 28 Nov 2019 14:21:11 GMT express:router:route source '*'
[ng] Thu, 28 Nov 2019 14:21:11 GMT express:router:layer new '/'
[ng] Thu, 28 Nov 2019 14:21:11 GMT express:router:route subscribe '*'
[ng] Thu, 28 Nov 2019 14:21:11 GMT express:router:layer new '/'
[ng] Thu, 28 Nov 2019 14:21:11 GMT express:router:route trace '*'
[ng] Thu, 28 Nov 2019 14:21:11 GMT express:router:layer new '/'
[ng] Thu, 28 Nov 2019 14:21:11 GMT express:router:route unbind '*'
[ng] Thu, 28 Nov 2019 14:21:11 GMT express:router:layer new '/'
[ng] Thu, 28 Nov 2019 14:21:11 GMT express:router:route unlink '*'
[ng] Thu, 28 Nov 2019 14:21:11 GMT express:router:layer new '/'
[ng] Thu, 28 Nov 2019 14:21:11 GMT express:router:route unlock '*'
[ng] Thu, 28 Nov 2019 14:21:11 GMT express:router:layer new '/'
[ng] Thu, 28 Nov 2019 14:21:11 GMT express:router:route unsubscribe '*'
[ng] Thu, 28 Nov 2019 14:21:11 GMT express:router:layer new '/'
[ng] Thu, 28 Nov 2019 14:21:11 GMT express:router use '/' middleware
[ng] Thu, 28 Nov 2019 14:21:11 GMT express:router:layer new '/'
[ng] Thu, 28 Nov 2019 14:21:11 GMT express:router use '/' <anonymous>
[ng] Thu, 28 Nov 2019 14:21:11 GMT express:router:layer new '/'
[ng] Thu, 28 Nov 2019 14:21:11 GMT express:router use '/' middleware
[ng] Thu, 28 Nov 2019 14:21:11 GMT express:router:layer new '/'
[ng] Thu, 28 Nov 2019 14:21:11 GMT express:router:route new '*'
[ng] Thu, 28 Nov 2019 14:21:11 GMT express:router:layer new '*'
[ng] Thu, 28 Nov 2019 14:21:11 GMT express:router:route get '*'
[ng] Thu, 28 Nov 2019 14:21:11 GMT express:router:layer new '/'
[INFO] Waiting for connectivity with ng...
Starting the Ionic dev server timed out (30000 ms)



** Below Throws and error**
**Not The Demo App but My App**
**$ ionic cordova run android -lcs**

> ng.cmd run app:ionic-cordova-serve --host=localhost --port=8100 --platform=android
[ng] Your global Angular CLI version (8.3.15) is greater than your local
[ng] version (7.2.1). The local Angular CLI version is used.
[ng] To disable this warning use "ng config -g cli.warnings.versionMismatch false".
[INFO] Waiting for connectivity with ng...
[INFO] Waiting for connectivity with ng...
[INFO] Waiting for connectivity with ng...
[INFO] Waiting for connectivity with ng...

[INFO] Development server running!

       Local: http://localhost:8100

       Use Ctrl+C to quit this process

> cordova.cmd build android
> native-run.cmd android --app platforms\android\app\build\outputs\apk\debug\app-debug.apk --forward 8100:8100
[native-run] No hardware devices found, attempting emulator...
[native-run] Selected emulator emulator-5554
[native-run] Forwarded device port 8100 to host port 8100
[native-run] Installing platforms\android\app\build\outputs\apk\debug\app-debug.apk...
[native-run] ERR_UNKNOWN: Non-zero exit code from adb: 1
[ERROR] An error occurred while running subprocess native-run.

        native-run.cmd android --app platforms\android\app\build\outputs\apk\debug\app-d... exited with exit code 1.

        Re-running this command with the --verbose flag may provide more information







**Runs Successfully**
**max-old-space-size=8192; ionic cordova run android -lcs**
**Unable to Debug**

ng.cmd run app:ionic-cordova-serve --host=localhost --port=8100 --platform=android
[ng] Your global Angular CLI version (8.3.15) is greater than your local
[ng] version (7.2.1). The local Angular CLI version is used.
[ng] To disable this warning use "ng config -g cli.warnings.versionMismatch false".
[INFO] Waiting for connectivity with ng...
[INFO] Waiting for connectivity with ng...
[INFO] Waiting for connectivity with ng...
[INFO] Waiting for connectivity with ng...

[INFO] Development server running!

       Local: http://localhost:8100

       Use Ctrl+C to quit this process

> cordova.cmd build android
> native-run.cmd android --app platforms\android\app\build\outputs\apk\debug\app-debug.apk --forward 8100:8100
[native-run] No hardware devices found, attempting emulator...
[native-run] Selected emulator emulator-5554
[native-run] Forwarded device port 8100 to host port 8100
[native-run] Installing platforms\android\app\build\outputs\apk\debug\app-debug.apk...
[native-run] Starting application activity com.deighton.dtimsgo/com.deighton.dtimsgo.MainActivity...
[ng] i ｢wdm｣: wait until bundle finished: /
[native-run] Run Successful

  ───────────────────────────────────────────────

     Ionic CLI update available: 5.4.5 → 5.4.9
           Run npm i -g ionic to update

  ───────────────────────────────────────────────

[ng]
[ng] Date: 2019-11-28T14:44:18.657Z
[ng] Hash: da39cd23d791721c5028
[ng] Time: 81926ms
[ng] chunk {common} common.js, common.js.map (common) 14.7 kB  [rendered]
[ng] chunk {cordova} cordova.js, cordova.js.map (cordova) 63.5 kB [entry] [rendered]
[ng] chunk {main} main.js, main.js.map (main) 5.81 MB [initial] [rendered]
[ng] chunk {polyfills} polyfills.js, polyfills.js.map (polyfills) 513 kB [initial] [rendered]
[ng] chunk {runtime} runtime.js, runtime.js.map (runtime) 8.98 kB [entry] [rendered]
[ng] chunk {styles} styles.js, styles.js.map (styles) 3.19 MB [initial] [rendered]
[ng] chunk {vendor} vendor.js, vendor.js.map (vendor) 20.1 MB [initial] [rendered]
[INFO] ... and 94 additional chunks
[ng] i ｢wdm｣: Compiled successfull

**Comment by navs007** [comment] 2019-11-28 15:31
**Outputs**
**Output of the Debug Console (View -> Toggle Debug Console -> Select Run Android on device or Run Android on emulator in ListBox):**
[RunAndroid ondeviceDemoApp.txt](https://github.com/microsoft/vscode-cordova/files/3902292/RunAndroid.ondeviceDemoApp.txt)


Attched The File

**Comment by RedMickey** [comment] 2019-12-02 12:49
@navs007, we figured out that it's possible to set maximum available memory size by using the `NODE_OPTIONS` global system variable, which has been introduced since Node.js 8. On Windows you can specify the number of available memory size the following way:
1. Open PowerShell
1. Execute the command below to set max-old-space-size parameter on 4096 Mb:
```
[Environment]::SetEnvironmentVariable("NODE_OPTIONS", "--max-old-space-size=4096", [System.EnvironmentVariableTarget]::User)
```
As seen from your logs of the demo application `native-run` package didn't complete the launch of the app, and the log entry `[native-run] Run Successful` wasn't print. This entry is the trigger to attachment to running app. So debugging didn't start.
We also tried to reproduce this error:
```
native-run.cmd android --app platforms\android\app\build\outputs\apk\debug\app-d... exited with exit code 1.
Re-running this command with the `--verbose` flag may provide more information
```
We added the global system variable `NODE_OPTIONS`, containing the value `--max-old-space-size=512` and then tried to execute the following command:
```
ionic cordova run android -lcs
```
The application launched successfully and we were able to attach and debug it.
But when we tried to launch the application again we got the same error as yours, since Android emulator completely froze. So we had to wipe emulator data and restart the command. So might be that this behavior is not connected with Node.js memory settings, but with Android Emulator snapshot bug.
Could you please do the following steps and try to debug the demo application again:
1. Specify the number of available memory size using global system variable `NODE_OPTIONS` as described above
1. Wipe Android emulator's data using Android Virtual Device Manager in Android Studio or in system terminal
   1 Open Android Studio
   2 In the toolbar select `AVD Manager` icon and open `Android Virtual Device Manager`
   3 Select the used device and click on dropdown icon at the Actions column
   4 Select `Wipe Data` item
1. Try to debug the demo application using `Run Android on emulator` debug scenario

If `Run Android on emulator` debug scenario fails, could you please do the following steps:
1. Send us output of the Debug Console for `Run Android on emulator` scenario
1. Execute the command `ionic cordova run android -cs` (without livereloads) to launch the application.
1. If the application stars successfully, try to attach to it using `Attach to running android on emulator` scenario
1. Please send us output of the Debug Console for `Attach to running android on emulator` scenario or an error message if the launch command fails

**Comment by navs007** [comment] 2019-12-02 15:07
HI 
**step 1**
I have executed the command in powershell.

**Step 2**
Package.json file

 "scripts": {
        "ng": "ng",
        "start": "node --max_old_space_size=8192 ./node_modules/@angular/cli/bin/ng serve",
        "build": "node --max_old_space_size=8192 ./node_modules/@angular/cli/bin/build"      
    },

**Step 3** Not working

First time debug works ie "Attach the debug on Emulator" and suddenly it crashes and debugger detaches and after that, I did try wiping  off the data.
Attach the module does not attach

**Step 4**

After adding the step 1 now my application thats running on emulator crashes suddenly and will have to load data again.In my app Every time ie the first time , the data load is high, corresponding loads are smaller.
Because the emulator s crashing even before all the data is loaded , all im doing is logging in and waiting and emulator crashed and again log in and emulator crashes.

So I went ahead and removed the environment variable of Node_Options.
Its not crashing atleast while im not debugging.

![ChromeInspect](https://user-images.githubusercontent.com/57499616/69969779-132fef00-14eb-11ea-9dca-6b7d678ccf9c.PNG)



Attached is the screenshot of Devlopertools , Debug Console vsc, and ChromeInspect...ie what is expected in debug console vsc too
![ChromeInspect](https://user-images.githubusercontent.com/57499616/69969640-cea45380-14ea-11ea-8164-2fc0386e2920.PNG)
![debugconsole](https://user-images.githubusercontent.com/57499616/69969641-cea45380-14ea-11ea-8416-41b185bc5d92.PNG)
![helpdevelopertool](https://user-images.githubusercontent.com/57499616/69969644-cea45380-14ea-11ea-9882-0aafdff1aa3f.PNG)


...

**Comment by RedMickey** [comment] 2019-12-04 11:47
@navs007, unfortunately we cannot give any certain reasons of crushes of your application because we don't have an opportunity to completely investigate it since we don't have a fully configured demo to run.

* As you said the `Run Android on emulator` debug scenario hadn't worked for the demo application. Could you please start the demo application using the following command (without livereloads) and then try to attach to it using the extension:
    ```
    ionic cordova run android
    ```
    If it doesn't work then specify memory size parameter as before:
    ```
    max-old-space-size=8192; ionic cordova run android
    ```
    We tested that demo app without any memory size specifications and didn't face any problems on debugging. However when we specified fairly small memory size, there was a problem with a lack of memory. Then we removed `max-old-space-size` parameter and the demo launched without problems.

* If the demo application cannot be debugged at all, could you please create plain Ionic app and try to debug it using the extension's `Run Android on emulator` and `Attach to running android on emulator` scenarios? 
    You can create a plain Ionic application the following way:
    ```
    ionic start ionic4_app tabs --cordova --type=angular --no-link
    cd ionic4_app
    ionic cordova platform add android
    ```
    We also were able to debug a plain application using `Run Android on emulator` scenario without problems.

    If you face any problems, please send us info about them:
    * Screenshot with code causing the problem
    * Logs from the Debug Console
    * Description of steps to reproduce the problem

    Please let us know about your results.

* Could you please also open your project and run the following commands and send us their outputs? It will be helpful for better understanding of the situation from our side. You can send outputs to my working email v-miezhe@microsoft.com if you wish.
    ```
    cordova info
    ```
    ```
    ionic info  
    ```

**Comment by NavyaRagha** [comment] 2019-12-04 14:23
Unfortunately I cannot share the Project,As I do not own it.
How ever I will close this issue, As I have chrome://inspect as an alternative to debug.

Some inputs for you to may be consider in the next phase release may be
**Attach to running android on device/ Emulator**
Note my project stores huge huge sql data when offline and online locally.
and some unhand led errors which might be the reason for crashing.

or too many breakpoints (chrome crashes too , but when I attach it back it picks up the break point)

1.When the App crashes , I tried attaching my App does not work.  
2.When the App crashes , I tried attaching demo app does not work.

Note I wiped off the Data and restarted the app too and some times just wiped the data both scenarios did not work.

**Attach to running android on device**
Both My app and ur demo app works.

When I change some settings ,I am able to Attach , however
The behavior is not consistent, I might keep a eye on it and post here ,if I have any findings.

Some suggest restarting the device would help attach, I will try that as a last resort and keep you updated.

Thanks for you help in trying to help me.Appreciate your dedication to not give up.

**Comment by NavyaRagha** [comment] 2019-12-04 14:58
Well This is doing the trick for Me on
**Attach to running android on device**

Run the app using the command 
--max-old-space-size=8192; ionic cordova run android -lcs

Once the app is loaded, Attach to running Android On Device the app wont debug.

So go to the device and in **"Developer Options"** **"Select debug app"**
 Try attaching the debugger again , Breaks with the attached error 
![Capture](https://user-images.githubusercontent.com/8824736/70152983-2a521680-167c-11ea-920d-185a570be9ed.PNG)


No go back to **"Developer Options"** **"Select debug app"** and undo the app selected.

Attach the Debugger Again , did attach . This trick worked for continuous 2 attempts.
Hope it does it always.

**Comment by RedMickey** [comment] 2019-12-05 11:43
@NavyaRagha, with respect to this trick, we tried to reproduce it and figured out that `Unable to find localabstract name of cordova app` error is thrown when `Wait for debugger` option is enabled in the `Developer Options`. We noticed that in case of enabled `Wait for debugger` option, the socket `@webview_devtools_remote_process_ID` was not created. The extension uses it to take process ID that is required to attach to a device. Therefore attach scenario fails. But when we disabled `Wait for debugger` option, the debugger did attach correctly.

**Comment by NavyaRagha** [comment] 2019-12-05 13:15
Hi , With the above trick the App always attaches and breaks on the break point too..but im unable to read the values on move over or the watch window.Attached is the screen shot of the same.

![Capture](https://user-images.githubusercontent.com/8824736/70238408-351db180-1737-11ea-87ea-b6a1e6c327b5.PNG)

 Can you let me know , how to fix that..

**Comment by RedMickey** [comment] 2019-12-06 08:47
@NavyaRagha, it seems that the original problem discussed in this issue has been solved, so I'm closing this. But with respect to watching and evaluating variables problem I opened the new issue.

**Closed by RedMickey** 2019-12-06 08:47 UTC
Labels: need-more-info, needrepro
