### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by Fenikz31** [microsoft/vscode-cordova#573] opened 2019-09-27 07:23 UTC
[msjsdiag.cordova-tools-unresponsive.cpuprofile.txt](https://github.com/microsoft/vscode-cordova/files/3661449/msjsdiag.cordova-tools-unresponsive.cpuprofile.txt)
- Issue Type: `Performance`
- Extension Name: `cordova-tools`
- Extension Version: `1.8.6`
- OS Version: `Windows_NT x64 10.0.18985`
- VSCode version: `1.38.1`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`C:\Users\Fenikz\msjsdiag.cordova-tools-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/Microsoft/vscode/wiki/Explain:-extension-causes-high-cpu-load

**Comment by SounD120** [comment] 2019-09-27 07:39
Hi @Fenikz31 . As seen from your cpu profile extension activation caused the high cpu load. Do you remember what did you do in VS Code when this message showed up?

**Comment by Fenikz31** [comment] 2019-09-27 20:10
Well, I just turned on my laptop and launch vscode. Maybe there was some
services running in the background.

Le ven. 27 sept. 2019 09:40, Yuri Skorokhodov <notifications@github.com> a
écrit :

**Comment by SounD120** [comment] 2019-09-30 13:26
@Fenikz31 Thanks for clarification. Since this behavior is connected with high cpu load on the extension activation, I am closing this issue as a duplicate of #517.

**Closed by SounD120** 2019-09-30 13:26 UTC
Labels: duplicate, performance
