### ISSUE TITLE
TypeError: Cannot read property 'Runtime' of undefined

### ISSUE THREAD

**Issue by jepiqueau** [Microsoft/vscode-cordova#241] opened 2017-02-08 14:32 UTC
Since i upgrade on my Windows 10 Desktop to 
Visual Studio Code V 1.9.0
Date 2017-02-02
Interpreteur de commandes 1.4.6
Convertisseur 53.0.2785.143
NODE 6.5.0

and Cordova Tools 1.2.6

i got the following error message when i run Android on Device a Ionic 2 application

this was not the case before the upgrade
can you please help

Error processing "evaluate": TypeError: Cannot read property 'Runtime' of undefined
    at CordovaDebugAdapter.globalEvaluate (C:\Users\Jean-Pierre\.vscode\extensions\vsmobile.cordova-tools-1.2.6\node_modules\vscode-chrome-debug-core\out\src\chrome\chromeDebugAdapter.js:1021:27)
    at CordovaDebugAdapter.evaluate (C:\Users\Jean-Pierre\.vscode\extensions\vsmobile.cordova-tools-1.2.6\node_modules\vscode-chrome-debug-core\out\src\chrome\chromeDebugAdapter.js:943:32)
    at dispatchRequest (C:\Users\Jean-Pierre\.vscode\extensions\vsmobile.cordova-tools-1.2.6\node_modules\vscode-chrome-debug-core\out\src\chrome\chromeDebugSession.js:122:68)
    at ProtocolServer._handleData (C:\Users\Jean-Pierre\.vscode\extensions\vsmobile.cordova-tools-1.2.6\node_modules\vscode-chrome-debug-core\node_modules\vscode-debugadapter\lib\protocol.js:104:38)
    at Socket.<anonymous> (C:\Users\Jean-Pierre\.vscode\extensions\vsmobile.cordova-tools-1.2.6\node_modules\vscode-chrome-debug-core\node_modules\vscode-debugadapter\lib\protocol.js:24:60)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    at Pipe.onread (net.js:543:20)

**Comment by vladimir-kotikov** [comment] 2017-02-08 16:03
Hey @jepiqueau, thanks for reporting the issue! Could you please try setting `"verboseDiagnosticLogging": true` in your launch configuration, launch debug again and post output from debug console here? This would help us to better understand what might be the cause here.

**Comment by jepiqueau** [comment] 2017-02-09 10:10
Please  find the output of debug console


   Error processing "evaluate": TypeError: Cannot read property 
'Runtime' of undefined
     at CordovaDebugAdapter.globalEvaluate 
(C:\Users\Jean-Pierre\.vscode\extensions\vsmobile.cordova-tools-1.2.6\node_modules\vscode-chrome-debug-core\out\src\chrome\chromeDebugAdapter.js:1021:27)
     at CordovaDebugAdapter.evaluate 
(C:\Users\Jean-Pierre\.vscode\extensions\vsmobile.cordova-tools-1.2.6\node_modules\vscode-chrome-debug-core\out\src\chrome\chromeDebugAdapter.js:943:32)
     at dispatchRequest 
(C:\Users\Jean-Pierre\.vscode\extensions\vsmobile.cordova-tools-1.2.6\node_modules\vscode-chrome-debug-core\out\src\chrome\chromeDebugSession.js:122:68)
     at ProtocolServer._handleData 
(C:\Users\Jean-Pierre\.vscode\extensions\vsmobile.cordova-tools-1.2.6\node_modules\vscode-chrome-debug-core\node_modules\vscode-debugadapter\lib\protocol.js:104:38)
     at Socket.<anonymous> 
(C:\Users\Jean-Pierre\.vscode\extensions\vsmobile.cordova-tools-1.2.6\node_modules\vscode-chrome-debug-core\node_modules\vscode-debugadapter\lib\protocol.js:24:60)
     at emitOne (events.js:96:13)
     at Socket.emit (events.js:188:7)
     at readableAddChunk (_stream_readable.js:176:18)
     at Socket.Readable.push (_stream_readable.js:134:10)
     at Pipe.onread (net.js:543:20)
›To client: 
{"seq":0,"type":"response","request_seq":1,"command":"evaluate","success":false,"message":"[cordova-tools] 
Error processing \"evaluate\": TypeError: Cannot read property 'Runtime' 
of undefined\n    at CordovaDebugAdapter.globalEvaluate 
(C:\\Users\\Jean-Pierre\\.vscode\\extensions\\vsmobile.cordova-tools-1.2.6\\node_modules\\vscode-chrome-debug-core\\out\\src\\chrome\\chromeDebugAdapter.js:1021:27)\n 
at CordovaDebugAdapter.evaluate 
(C:\\Users\\Jean-Pierre\\.vscode\\extensions\\vsmobile.cordova-tools-1.2.6\\node_modules\\vscode-chrome-debug-core\\out\\src\\chrome\\chromeDebugAdapter.js:943:32)\n 
at dispatchRequest 
(C:\\Users\\Jean-Pierre\\.vscode\\extensions\\vsmobile.cordova-tools-1.2.6\\node_modules\\vscode-chrome-debug-core\\out\\src\\chrome\\chromeDebugSession.js:122:68)\n 
at ProtocolServer._handleData 
(C:\\Users\\Jean-Pierre\\.vscode\\extensions\\vsmobile.cordova-tools-1.2.6\\node_modules\\vscode-chrome-debug-core\\node_modules\\vscode-debugadapter\\lib\\protocol.js:104:38)\n 
at Socket.<anonymous> 
(C:\\Users\\Jean-Pierre\\.vscode\\extensions\\vsmobile.cordova-tools-1.2.6\\node_modules\\vscode-chrome-debug-core\\node_modules\\vscode-debugadapter\\lib\\protocol.js:24:60)\n 
at emitOne (events.js:96:13)\n    at Socket.emit (events.js:188:7)\n    
at readableAddChunk (_stream_readable.js:176:18)\n    at 
Socket.Readable.push (_stream_readable.js:134:10)\n    at Pipe.onread 
(net.js:543:20)","body":{"error":{"id":1104,"format":"[{_extensionName}] 
Error pro[...]
   ›From client: evaluate({"expression":"pluginResult","context":"watch"})
Error processing "evaluate": TypeError: Cannot read property 'Runtime' 
of undefined
     at CordovaDebugAdapter.globalEvaluate 
(C:\Users\Jean-Pierre\.vscode\extensions\vsmobile.cordova-tools-1.2.6\node_modules\vscode-chrome-debug-core\out\src\chrome\chromeDebugAdapter.js:1021:27)
     at CordovaDebugAdapter.evaluate 
(C:\Users\Jean-Pierre\.vscode\extensions\vsmobile.cordova-tools-1.2.6\node_modules\vscode-chrome-debug-core\out\src\chrome\chromeDebugAdapter.js:943:32)
     at dispatchRequest 
(C:\Users\Jean-Pierre\.vscode\extensions\vsmobile.cordova-tools-1.2.6\node_modules\vscode-chrome-debug-core\out\src\chrome\chromeDebugSession.js:122:68)
     at ProtocolServer._handleData 
(C:\Users\Jean-Pierre\.vscode\extensions\vsmobile.cordova-tools-1.2.6\node_modules\vscode-chrome-debug-core\node_modules\vscode-debugadapter\lib\protocol.js:104:38)
     at Socket.<anonymous> 
(C:\Users\Jean-Pierre\.vscode\extensions\vsmobile.cordova-tools-1.2.6\node_modules\vscode-chrome-debug-core\node_modules\vscode-debugadapter\lib\protocol.js:24:60)
     at emitOne (events.js:96:13)
     at Socket.emit (events.js:188:7)
     at readableAddChunk (_stream_readable.js:176:18)
     at Socket.Readable.push (_stream_readable.js:134:10)
     at Pipe.onread (net.js:543:20)
  ›To client: 
{"seq":0,"type":"response","request_seq":2,"command":"evaluate","success":false,"message":"[cordova-tools] 
Error processing \"evaluate\": TypeError: Cannot read property 'Runtime' 
of undefined\n    at CordovaDebugAdapter.globalEvaluate 
(C:\\Users\\Jean-Pierre\\.vscode\\extensions\\vsmobile.cordova-tools-1.2.6\\node_modules\\vscode-chrome-debug-core\\out\\src\\chrome\\chromeDebugAdapter.js:1021:27)\n 
at CordovaDebugAdapter.evaluate 
(C:\\Users\\Jean-Pierre\\.vscode\\extensions\\vsmobile.cordova-tools-1.2.6\\node_modules\\vscode-chrome-debug-core\\out\\src\\chrome\\chromeDebugAdapter.js:943:32)\n 
at dispatchRequest 
(C:\\Users\\Jean-Pierre\\.vscode\\extensions\\vsmobile.cordova-tools-1.2.6\\node_modules\\vscode-chrome-debug-core\\out\\src\\chrome\\chromeDebugSession.js:122:68)\n 
at ProtocolServer._handleData 
(C:\\Users\\Jean-Pierre\\.vscode\\extensions\\vsmobile.cordova-tools-1.2.6\\node_modules\\vscode-chrome-debug-core\\node_modules\\vscode-debugadapter\\lib\\protocol.js:104:38)\n 
at Socket.<anonymous> 
(C:\\Users\\Jean-Pierre\\.vscode\\extensions\\vsmobile.cordova-tools-1.2.6\\node_modules\\vscode-chrome-debug-core\\node_modules\\vscode-debugadapter\\lib\\protocol.js:24:60)\n 
at emitOne (events.js:96:13)\n    at Socket.emit (events.js:188:7)\n    
at readableAddChunk (_stream_readable.js:176:18)\n    at 
Socket.Readable.push (_stream_readable.js:134:10)\n    at Pipe.onread 
(net.js:543:20)","body":{"error":{"id":1104,"format":"[{_extensionName}] 
Error pro[...]
   ›From client: evaluate({"expression":"pluginObj","context":"watch"})
Error processing "evaluate": TypeError: Cannot read property 'Runtime' 
of undefined
     at CordovaDebugAdapter.globalEvaluate 
(C:\Users\Jean-Pierre\.vscode\extensions\vsmobile.cordova-tools-1.2.6\node_modules\vscode-chrome-debug-core\out\src\chrome\chromeDebugAdapter.js:1021:27)
     at CordovaDebugAdapter.evaluate 
(C:\Users\Jean-Pierre\.vscode\extensions\vsmobile.cordova-tools-1.2.6\node_modules\vscode-chrome-debug-core\out\src\chrome\chromeDebugAdapter.js:943:32)
     at dispatchRequest 
(C:\Users\Jean-Pierre\.vscode\extensions\vsmobile.cordova-tools-1.2.6\node_modules\vscode-chrome-debug-core\out\src\chrome\chromeDebugSession.js:122:68)
     at ProtocolServer._handleData 
(C:\Users\Jean-Pierre\.vscode\extensions\vsmobile.cordova-tools-1.2.6\node_modules\vscode-chrome-debug-core\node_modules\vscode-debugadapter\lib\protocol.js:104:38)
     at Socket.<anonymous> 
(C:\Users\Jean-Pierre\.vscode\extensions\vsmobile.cordova-tools-1.2.6\node_modules\vscode-chrome-debug-core\node_modules\vscode-debugadapter\lib\protocol.js:24:60)
     at emitOne (events.js:96:13)
     at Socket.emit (events.js:188:7)
     at readableAddChunk (_stream_readable.js:176:18)
     at Socket.Readable.push (_stream_readable.js:134:10)
     at Pipe.onread (net.js:543:20)
›To client: 
{"seq":0,"type":"response","request_seq":3,"command":"evaluate","success":false,"message":"[cordova-tools] 
Error processing \"evaluate\": TypeError: Cannot read property 'Runtime' 
of undefined\n    at CordovaDebugAdapter.globalEvaluate 
(C:\\Users\\Jean-Pierre\\.vscode\\extensions\\vsmobile.cordova-tools-1.2.6\\node_modules\\vscode-chrome-debug-core\\out\\src\\chrome\\chromeDebugAdapter.js:1021:27)\n 
at CordovaDebugAdapter.evaluate 
(C:\\Users\\Jean-Pierre\\.vscode\\extensions\\vsmobile.cordova-tools-1.2.6\\node_modules\\vscode-chrome-debug-core\\out\\src\\chrome\\chromeDebugAdapter.js:943:32)\n 
at dispatchRequest 
(C:\\Users\\Jean-Pierre\\.vscode\\extensions\\vsmobile.cordova-tools-1.2.6\\node_modules\\vscode-chrome-debug-core\\out\\src\\chrome\\chromeDebugSession.js:122:68)\n 
at ProtocolServer._handleData 
(C:\\Users\\Jean-Pierre\\.vscode\\extensions\\vsmobile.cordova-tools-1.2.6\\node_modules\\vscode-chrome-debug-core\\node_modules\\vscode-debugadapter\\lib\\protocol.js:104:38)\n 
at Socket.<anonymous> 
(C:\\Users\\Jean-Pierre\\.vscode\\extensions\\vsmobile.cordova-tools-1.2.6\\node_modules\\vscode-chrome-debug-core\\node_modules\\vscode-debugadapter\\lib\\protocol.js:24:60)\n 
at emitOne (events.js:96:13)\n    at Socket.emit (events.js:188:7)\n    
at readableAddChunk (_stream_readable.js:176:18)\n    at 
Socket.Readable.push (_stream_readable.js:134:10)\n    at Pipe.onread 
(net.js:543:20)","body":{"error":{"id":1104,"format":"[{_extensionName}] 
Error pro[...]
   ›From client: evaluate({"expression":"methodName","context":"watch"})
Error processing "evaluate": TypeError: Cannot read property 'Runtime' 
of undefined
     at CordovaDebugAdapter.globalEvaluate 
(C:\Users\Jean-Pierre\.vscode\extensions\vsmobile.cordova-tools-1.2.6\node_modules\vscode-chrome-debug-core\out\src\chrome\chromeDebugAdapter.js:1021:27)
     at CordovaDebugAdapter.evaluate 
(C:\Users\Jean-Pierre\.vscode\extensions\vsmobile.cordova-tools-1.2.6\node_modules\vscode-chrome-debug-core\out\src\chrome\chromeDebugAdapter.js:943:32)
     at dispatchRequest 
(C:\Users\Jean-Pierre\.vscode\extensions\vsmobile.cordova-tools-1.2.6\node_modules\vscode-chrome-debug-core\out\src\chrome\chromeDebugSession.js:122:68)
     at ProtocolServer._handleData 
(C:\Users\Jean-Pierre\.vscode\extensions\vsmobile.cordova-tools-1.2.6\node_modules\vscode-chrome-debug-core\node_modules\vscode-debugadapter\lib\protocol.js:104:38)
     at Socket.<anonymous> 
(C:\Users\Jean-Pierre\.vscode\extensions\vsmobile.cordova-tools-1.2.6\node_modules\vscode-chrome-debug-core\node_modules\vscode-debugadapter\lib\protocol.js:24:60)
     at emitOne (events.js:96:13)
     at Socket.emit (events.js:188:7)
     at readableAddChunk (_stream_readable.js:176:18)
     at Socket.Readable.push (_stream_readable.js:134:10)
     at Pipe.onread (net.js:543:20)
›To client: 
{"seq":0,"type":"response","request_seq":4,"command":"evaluate","success":false,"message":"[cordova-tools] 
Error processing \"evaluate\": TypeError: Cannot read property 'Runtime' 
of undefined\n    at CordovaDebugAdapter.globalEvaluate 
(C:\\Users\\Jean-Pierre\\.vscode\\extensions\\vsmobile.cordova-tools-1.2.6\\node_modules\\vscode-chrome-debug-core\\out\\src\\chrome\\chromeDebugAdapter.js:1021:27)\n 
at CordovaDebugAdapter.evaluate 
(C:\\Users\\Jean-Pierre\\.vscode\\extensions\\vsmobile.cordova-tools-1.2.6\\node_modules\\vscode-chrome-debug-core\\out\\src\\chrome\\chromeDebugAdapter.js:943:32)\n 
at dispatchRequest 
(C:\\Users\\Jean-Pierre\\.vscode\\extensions\\vsmobile.cordova-tools-1.2.6\\node_modules\\vscode-chrome-debug-core\\out\\src\\chrome\\chromeDebugSession.js:122:68)\n 
at ProtocolServer._handleData 
(C:\\Users\\Jean-Pierre\\.vscode\\extensions\\vsmobile.cordova-tools-1.2.6\\node_modules\\vscode-chrome-debug-core\\node_modules\\vscode-debugadapter\\lib\\protocol.js:104:38)\n 
at Socket.<anonymous> 
(C:\\Users\\Jean-Pierre\\.vscode\\extensions\\vsmobile.cordova-tools-1.2.6\\node_modules\\vscode-chrome-debug-core\\node_modules\\vscode-debugadapter\\lib\\protocol.js:24:60)\n 
at emitOne (events.js:96:13)\n    at Socket.emit (events.js:188:7)\n    
at readableAddChunk (_stream_readable.js:176:18)\n    at 
Socket.Readable.push (_stream_readable.js:134:10)\n    at Pipe.onread 
(net.js:543:20)","body":{"error":{"id":1104,"format":"[{_extensionName}] 
Error pro[...]
   ›From client: evaluate({"expression":"args","context":"watch"})



**** and so on 11 times in total ****

**** the console message after the 11 times are the following ****

›From client: 
initialize({"adapterID":"cordova","pathFormat":"path","linesStartAt1":true,"columnsStartAt1":true,"supportsVariableType":true,"supportsVariablePaging":true,"supportsRunInTerminalRequest":true})
   ›To client: 
{"seq":0,"type":"response","request_seq":12,"command":"initialize","success":true,"body":{"exceptionBreakpointFilters":[{"label":"All 
Exceptions","filter":"all","default":false},{"label":"Uncaught 
Exceptions","filter":"uncaught","default":true}],"supportsConfigurationDoneRequest":true,"supportsSetVariable":true,"supportsConditionalBreakpoints":true,"supportsCompletionsRequest":true,"supportsHitConditionalBreakpoints":true}}
   ›From client: launch({"name":"Run Android on 
device","type":"cordova","request":"launch","platform":"android","target":"device","port":9222,"sourceMaps":true,"cwd":"g:\\Ionic2Apps\\SBM-Investor-Relations\\client\\InvestorRelations","ionicLiveReload":false,"verboseDiagnosticLogging":true}) 


Discovering targets via http://127.0.0.1:9222/json
   ›Attaching to target: 
{"description":"{\"attached\":true,\"empty\":true,\"screenX\":0,\"screenY\":0,\"visible\":true}","devtoolsFrontendUrl":"http://chrome-devtools-frontend.appspot.com/serve_rev/@733808abc67b7fce93430fcb00127707bffe4639/inspector.html?ws=127.0.0.1:9222/devtools/page/4021dcad-68d5-4bf6-8604-ad6d3e844bf2","id":"4021dcad-68d5-4bf6-8604-ad6d3e844bf2","title":"file:///android_asset/www/index.html","type":"page","url":"file:///android_asset/www/index.html","webSocketDebuggerUrl":"ws://127.0.0.1:9222/devtools/page/4021dcad-68d5-4bf6-8604-ad6d3e844bf2"}
   ›WebSocket Url: 
ws://127.0.0.1:9222/devtools/page/4021dcad-68d5-4bf6-8604-ad6d3e844bf2
   ›To target: "{\"id\":1,\"method\":\"Console.enable\"}"
   ›To target: "{\"id\":2,\"method\":\"Debugger.enable\"}"
   ›To target: "{\"id\":3,\"method\":\"Runtime.enable\"}"
   ›To target: "{\"id\":4,\"method\":\"Runtime.runIfWaitingForDebugger\"}"
   ›To target: "{\"id\":5,\"method\":\"Runtime.run\"}"
   ›From target: 
{"method":"Console.messageAdded","params":{"message":{"source":"console-api","level":"info","text":"Ionic 
Storage 
driver:","url":"file:///android_asset/www/build/main.js","line":119209,"column":25}}}
   ›From target: {"id":1,"result":{}}
   ›From target: 
{"method":"Debugger.scriptParsed","params":{"scriptId":"27","url":"file:///android_asset/www/cordova.js","startLine":0,"startColumn":0,"endLine":2207,"endColumn":5,"executionContextId":1,"hash":"643271D101DA8C0554590174E8E1821B3A40EA57","executionContextAuxData":{"isDefault":true,"frameId":"1038.1"},"isLiveEdit":false,"sourceMapURL":"","hasSourceURL":false}}
Paths.scriptParsed: could not resolve 
file:///android_asset/www/cordova.js to a file in the workspace. 
webRoot: g:\Ionic2Apps\SBM-Investor-Relations\client\InvestorRelations
   ›From target: 
{"method":"Debugger.scriptParsed","params":{"scriptId":"28","url":"file:///android_asset/www/build/polyfills.js","startLine":0,"startColumn":0,"endLine":4,"endColumn":0,"executionContextId":1,"hash":"4E66263148B73E136970CAF1C17A21A8654AD365","executionContextAuxData":{"isDefault":true,"frameId":"1038.1"},"isLiveEdit":false,"sourceMapURL":"","hasSourceURL":false}}
Paths.scriptParsed: resolved 
file:///android_asset/www/build/polyfills.js to 
g:\Ionic2Apps\SBM-Investor-Relations\client\InvestorRelations\www\build\polyfills.js. 
webRoot: g:\Ionic2Apps\SBM-Investor-Relations\client\InvestorRelations

Paths.scriptParsed: could not resolve eval://29 to a file in the 
workspace. webRoot: 
g:\Ionic2Apps\SBM-Investor-Relations\client\InvestorRelations
   ›From target: 
{"method":"Debugger.scriptParsed","params":{"scriptId":"30","url":"","startLine":0,"startColumn":0,"endLine":3,"endColumn":2,"executionContextId":1,"hash":"52B6A052DE156707D2E00FF51017D482543400D6","executionContextAuxData":{"isDefault":true,"frameId":"1038.1"},"isLiveEdit":false,"sourceMapURL":"","hasSourceURL":false}}
Paths.scriptParsed: could not resolve eval://30 to a file in the 
workspace. webRoot: 
g:\Ionic2Apps\SBM-Investor-Relations\client\InvestorRelations
   ›From target: 
{"method":"Debugger.scriptParsed","params":{"scriptId":"31","url":"","startLine":0,"startColumn":0,"endLine":3,"endColumn":2,"executionContextId":1,"hash":"FA2DA8027B99D731274F00318686F393CBE44264","executionContextAuxData":{"isDefault":true,"frameId":"1038.1"},"isLiveEdit":false,"sourceMapURL":"","hasSourceURL":false}}
Paths.scriptParsed: could not resolve eval://31 to a file in the 
workspace. webRoot: 
g:\Ionic2Apps\SBM-Investor-Relations\client\InvestorRelations
   ›From target: 
{"method":"Debugger.scriptParsed","params":{"scriptId":"32","url":"","startLine":0,"startColumn":0,"endLine":3,"endColumn":2,"executionContextId":1,"hash":"646722F315EF70E4953AF603BDBF2D70221E2F90","executionContextAuxData":{"isDefault":true,"frameId":"1038.1"},"isLiveEdit":false,"sourceMapURL":"","hasSourceURL":false}}


   *** and so on ... ***



Hope this will help

Regards

Jean Pierre QUEAU
15 rue Gustave Deloye
06000 Nice France
tel: +33 7 68 26 71 22
email: jepi.queau@free.fr
        jeanpierre.queau@gmail.com

**Comment by vladimir-kotikov** [comment] 2017-02-09 12:59
@jepiqueau, thanks. Lookslike this is known issue with vscode and debug adapter we're using internally (see https://github.com/Microsoft/vscode/issues/17902), however this has been already fixed in latest version of debug adapter, so we just need to upgrade. I'll send a PR shortly

**Comment by jepiqueau** [comment] 2017-02-09 13:03
Many thanks, i know that it was known and solve already previously but 
the fix given was on typescript file where i got only the js file so i 
did'nt want to miss it up myself so that why i reported to you

looking forward the upgrade

Have a good day

Jean Pierre QUEAU
15 rue Gustave Deloye
06000 Nice France
tel: +33 7 68 26 71 22
email: jepi.queau@free.fr
        jeanpierre.queau@gmail.com

**Comment by vladimir-kotikov** [comment] 2017-02-09 13:07
Thanks!

Also, just a small additions - apart from that scary error message in debug console, all other debug functionality should be working fine, so you could continue using extension.

**Comment by jepiqueau** [comment] 2017-02-09 13:11
Many thanks, it is the way i worked for more than 6 months as i found 
the tool and the extensions really great and useful to develop apps. in 
case i found some other problems in the future which i hope not i will 
send them to you.

Regards

Jean Pierre QUEAU
15 rue Gustave Deloye
06000 Nice France
tel: +33 7 68 26 71 22
email: jepi.queau@free.fr
        jeanpierre.queau@gmail.com

**Comment by vladimir-kotikov** [comment] 2017-03-09 10:31
Closing this as #242 has been merged. Please expect new release in next couple of days.

**Closed by vladimir-kotikov** 2017-03-09 10:31 UTC

**Comment by mkoseoglu** [comment] 2017-05-06 23:18
I also do this on the NativeScript debug screen. Can you help me? @vladimir-kotikov
