### ISSUE TITLE
"Run Android on emulator" runs into endless loop without any error message in Debug Console

### ISSUE THREAD

**Issue by sanme98** [Microsoft/vscode-cordova#337] opened 2017-11-13 02:23 UTC
I running my Ionic 3 app in the Android emulator in Windows 10. But it failed to attach to the debugger. It only endless loop in the progress bar and the debug console shows nothing even after more than 5 minutes. adb devices shown the emulator already started and able to detect.

Any help?

![image](https://user-images.githubusercontent.com/5364763/32707070-4c29c1a6-c85c-11e7-8bae-4189b63312d3.png)

![image](https://user-images.githubusercontent.com/5364763/32707216-40d3cb2a-c85d-11e7-9062-895de39f6937.png)

**Comment by iTOYS** [comment] 2017-11-13 11:27
Hi @sanme98,
Seems like you have wrong configuration.
Please try to replace your `launch.json` to default and run again:
```
{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Run Android on device",
            "type": "cordova",
            "request": "launch",
            "platform": "android",
            "target": "device",
            "port": 9222,
            "sourceMaps": true,
            "cwd": "${workspaceRoot}",
            "ionicLiveReload": false
        },
        {
            "name": "Run iOS on device",
            "type": "cordova",
            "request": "launch",
            "platform": "ios",
            "target": "device",
            "port": 9220,
            "sourceMaps": true,
            "cwd": "${workspaceRoot}",
            "ionicLiveReload": false
        },
        {
            "name": "Attach to running android on device",
            "type": "cordova",
            "request": "attach",
            "platform": "android",
            "target": "device",
            "port": 9222,
            "sourceMaps": true,
            "cwd": "${workspaceRoot}"
        },
        {
            "name": "Attach to running iOS on device",
            "type": "cordova",
            "request": "attach",
            "platform": "ios",
            "target": "device",
            "port": 9220,
            "sourceMaps": true,
            "cwd": "${workspaceRoot}"
        },
        {
            "name": "Run Android on emulator",
            "type": "cordova",
            "request": "launch",
            "platform": "android",
            "target": "emulator",
            "port": 9222,
            "sourceMaps": true,
            "cwd": "${workspaceRoot}",
            "ionicLiveReload": false
        },
        {
            "name": "Run iOS on simulator",
            "type": "cordova",
            "request": "launch",
            "platform": "ios",
            "target": "emulator",
            "port": 9220,
            "sourceMaps": true,
            "cwd": "${workspaceRoot}",
            "ionicLiveReload": false
        },
        {
            "name": "Attach to running android on emulator",
            "type": "cordova",
            "request": "attach",
            "platform": "android",
            "target": "emulator",
            "port": 9222,
            "sourceMaps": true,
            "cwd": "${workspaceRoot}"
        },
        {
            "name": "Attach to running iOS on simulator",
            "type": "cordova",
            "request": "attach",
            "platform": "ios",
            "target": "emulator",
            "port": 9220,
            "sourceMaps": true,
            "cwd": "${workspaceRoot}"
        },
        {
            "name": "Serve to the browser (ionic serve)",
            "type": "cordova",
            "request": "launch",
            "platform": "serve",
            "cwd": "${workspaceRoot}",
            "devServerAddress": "localhost",
            "sourceMaps": true,
            "ionicLiveReload": true
        },
        {
            "name": "Simulate Android in browser",
            "type": "cordova",
            "request": "launch",
            "platform": "android",
            "target": "chrome",
            "simulatePort": 8000,
            "livereload": true,
            "sourceMaps": true,
            "cwd": "${workspaceRoot}"
        },
        {
            "name": "Simulate iOS in browser",
            "type": "cordova",
            "request": "launch",
            "platform": "ios",
            "target": "chrome",
            "simulatePort": 8000,
            "livereload": true,
            "sourceMaps": true,
            "cwd": "${workspaceRoot}"
        },
        {
            "name": "Run Browser",
            "type": "cordova",
            "request": "launch",
            "platform": "browser",
            "target": "chrome",
            "simulatePort": 8000,
            "livereload": true,
            "sourceMaps": true,
            "cwd": "${workspaceRoot}"
        }
    ]
}
```

Please, let me know about any results.

Thanks!

**Comment by sanme98** [comment] 2017-11-13 11:48
Hi @iTOYS,

Thank you for your reply.

I still got the same problem after applied the configuration. Please refer to screen below.

The progress bar still in the endless loop even I have killed the Android emulator.

VS Code version: 1.17.2 64 bit.
Windows 10 1709 

![image](https://user-images.githubusercontent.com/5364763/32724106-fc68cd20-c8aa-11e7-8880-808ae92bce66.png)

**Comment by iTOYS** [comment] 2017-11-13 12:41
How do you run app?

**Comment by sanme98** [comment] 2017-11-14 02:08
In VS Code Integrated Terminal, type in "ionic cordova emulate android" and run. It will auto start the Android emulator, deploy the app, and run the app automatically. 

I have tried to start the Android emulator first using Android Studio there, but I got the same result too.

**Comment by iTOYS** [comment] 2017-11-15 16:52
@sanme98 
Sorry, but I can't repro this issue(
![image](https://user-images.githubusercontent.com/4017593/32848721-393687a8-ca3e-11e7-8774-beb818c7eb42.png)

**Comment by andrewleech** [comment] 2018-01-24 05:27
I've got exactly the same problem. 

Newly installed Cordova Tools plugin (1.3.2) with an existing cordova project. 
Windows 10. 
VS-Code Insiders (1.20.0-insider, d21e6a3e)

launch.json: 
```
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Run Android on device",
            "type": "cordova",
            "request": "launch",
            "platform": "android",
            "target": "device",
            "port": 9222,
            "sourceMaps": true,
            "cwd": "${workspaceRoot}\\build",
            "ionicLiveReload": false
        },
        ...
```
My cordova root directory is in build folder. Running `cordova run android --device` in this folder works fine.

Trying both "Run Android on device" and "Attach to running android on device" results in the the Integrated TERMINAL tab (next to DEBUG CONSOLE) being brought to the foreground where a PS prompt is shown. Nothing else. DEBUG CONSOLE is blank, as is OUTPUT and PROBLEMS.
Just the little progress moving stripe as highlighted in the initial post keeps going and going, no way to stop. "Stop Debugging" command does nothing. I have to quit VS Code and restart to try debugging again.

**Comment by svekl** [comment] 2018-01-24 10:31
@andrewleech tried to reproduce your issue both on 1.19 and 1.20 version, but had no luck, may I, please, ask you to provide some minimum example project that reproduces it?

**Comment by CobusKruger** [comment] 2018-01-30 12:57
I can reproduce it.

I have a project that I run as either a standard website, or as a Cordova app. The tree structure looks like this:

```
root
  |--Mobile
  |     |--hooks
  |     |--platforms
  |     |--plugins
  |     |--www
  |
  |--Web
       |--src
       |--etc
       |--etc
       |--etc
```
This is a Typescript project, and when I compile it, the output goes to `/Mobile/www`, from where I can build my app.

For `cordova build android` I first need to change to the folder `/Mobile/` to avoid getting "...is not a Cordova-based project" error.

I have one launch.json in `/Mobile/.vscode/` and another in `/.vscode`. They look like the same, except for `"cwd"`:
```
        {
            "name": "Run Android on emulator",
            "type": "cordova",
            "request": "launch",
            "platform": "android",
            "target": "emulator",
            "sourceMaps": true,
            "port": 5554,
            "cwd": "${workspaceRoot}/Mobile/" <-- Used in /.vscode/launch.json
            "cwd": "${workspaceRoot}", <-- Used in /Mobile/.vscode/launch.json
        },
```

If I open `/` in VS Code, I get the hang described by the OP. If I open `/Mobile`, everything works as advertised. 

To me, it seems that `cwd` is either ignored, or not interpreted correctly. And my example matches with @sanme98 , who uses a subfolder named `/TutorialApp1/www` and @andrewleech , who uses a subfolder named `/build`.

**Comment by Refs** [comment] 2018-04-22 12:52
I just encountered same error.   the ${workspaceRoot} should be ionic project root directory which is generated by 'ionic start project '. so the .vscode/lanuch.json  should in the directory which contain 'platforms/' directory 

```
|-- ionic project root directory/
    |-- .vscode/
        |-- launch.json
    |-- platforms
    |-- src/ 
```

just try!

**Comment by nightwolf13** [comment] 2018-05-08 13:36
Have similar problem...
Debug Console trying again and again:

Command finished with error code 0: C:\Users\ATkachenko\AppData\Local\Android\sdk\platform-tools\adb.exe -s,emulator-5554,shell,ps
.Running adb shell command "ps" on target emulator-5554...

**Comment by iTOYS** [comment] 2018-05-11 12:59
Hi @nightwolf13 
Could you please share example project with us to reproduce?

Thanks!

**Comment by iTOYS** [comment] 2018-05-15 11:02
@nightwolf13 
For clarification, you already have Android 8.0 emulator run when you launch `Run Android on emulator` configuration?

**Comment by nightwolf13** [comment] 2018-05-15 11:09
@iTOYS 
Yes.. The full scenario:
1) I start android emulator
2) Run app on android emulator, usually after very first run it works..
3) After some time (probably reason is that i remove and add android platform) it stop launching app on emulator... Debug out shows error which i wrote previously..
When this bug occurs, even restarting of VS Code didn't work.. Only complete machine reboot could help..
I tried to restart adb tool (kill-server and the start-server) but it didn't help too.. Also tried some commands for adb to clear smth cached i think (got it from internet)... but it also didn't help.. So looks like the reason is something else..

**Comment by iTOYS** [comment] 2018-05-15 13:47
@nightwolf13 
I've been tried your case, sorry but all works fine for me.
Can you try if this works when you run `cordova run android --emulator` in your terminal?

Thanks!

**Comment by nightwolf13** [comment] 2018-05-15 13:49
@iTOYS 
It also doesn't work.. But it didn't show any message.. just stack at one moment..

**Comment by nightwolf13** [comment] 2018-05-15 14:04
@iTOYS 
I will try and let you know.. I switched to Android 5 emulator (which as i said works fine on my machine).. so i need some time to reuse and reproduce this bug with Android 8..

**Comment by nightwolf13** [comment] 2018-05-16 10:50
@iTOYS 
Reproduced this bug again..
But tried to run cordova run android --emulator, and it works.. (maybe last times i stopped earlier then necessary, because there is a moment of building apk, when points are showing progress, and it continued very long)..
After that trying to run app on emulator using VS Code again, and it stacked on the message i wrote above..

**Comment by iTOYS** [comment] 2018-05-16 11:59
@nightwolf13 
Finally caught this on Windows 10 and Android 8 Emulator.
Also could not run with `cordova run android --emulator`, the same behaviour.

**Comment by iTOYS** [comment] 2018-05-16 12:25
Tried on another Android 8 Emulator(Pixel XL) and all works fine.

**Comment by iTOYS** [comment] 2018-05-31 12:11
Please try to re-create your emulators to prevent this issue.
Closing for now, feel free to reopen if you still have this issue after re-create!

Thanks.

**Closed by iTOYS** 2018-05-31 12:11 UTC
Labels: external, triaged, windows

**Comment by tranquocbaodev** [comment] 2019-01-30 21:51
before run "cordova run android --verbose"
after re-debug

**Comment by youlc** [comment] 2019-08-22 14:55
Debug Console trying again and again:(Loop)

Command finished with error code 0: C:\Users\UserID\AppData\Local\Android\sdk\platform-tools\adb.exe -s,emulator-5554,shell,ps
.Running adb shell command "ps" on target emulator-5554...

You just need adjust emulator's System Datetime for your TimeZone and Real Time of your PC.
Then reboot emulator debug again. ok ... ^^
