### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by cillvius** [microsoft/vscode-cordova#638] opened 2020-07-15 18:57 UTC
- Issue Type: `Performance`
- Extension Name: `cordova-tools`
- Extension Version: `1.9.4`
- OS Version: `Windows_NT x64 10.0.19041`
- VSCode version: `1.46.1`

[msjsdiag.cordova-tools-unresponsive.cpuprofile.txt](https://github.com/microsoft/vscode-cordova/files/4927353/msjsdiag.cordova-tools-unresponsive.cpuprofile.txt)
Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load

**Comment by SounD120** [comment] 2020-07-21 07:12
Hi there @cillvius . I analyzed your CPU profile and it shows that the high CPU load was caused by the extension activation time, it is a known issue and as soon as the extension will be bundled to decrease the amount of files in it, that problem should be resolved. Closing as duplicate of #517

**Closed by SounD120** 2020-07-21 07:12 UTC
Labels: duplicate
