### ISSUE TITLE
Nothing in the DEBUG CONSOLE after attaching to running android on device 

### ISSUE THREAD

**Issue by AEiosApp** [microsoft/vscode-cordova#628] opened 2020-05-26 16:09 UTC
## Actual Behavior
1. Connect my android device
2. Build & run cordova project (vuejs + cordova) by
     cordova run android
3. hit Attach to running android device

![image](https://user-images.githubusercontent.com/19554725/82923556-c3cdf700-9f40-11ea-95fe-15e5bc48c3ae.png)

4. There is no printing of my console.log() in DEBUG CONSOLE

## Software versions
- Cordova VS Code extension version: 1.9.4
- VSCode version: 1.45.1
- OS platform and version: MacOS Catalina 10.15.4
- NodeJS version:
- Cordova version: 9.0.0
- Cordova-Android/iOS/Windows version: 8.1.0/5.1.1/na

**Comment by SounD120** [comment] 2020-05-28 07:57
Hi @AEiosApp and thanks for reaching us. Could you please provide us minimal demo application in which this problem is reproduced and steps reproduce it?

You can also try reinstalling Cordova Tools extension and reopening VS Code(it's important to close it completely and then reopen it to make sure that the extension is removed before new installation) before and let us know if this helped.

**Comment by SounD120** [comment] 2020-06-02 10:16
@AEiosApp Just a friendly ping on this.

**Comment by AEiosApp** [comment] 2020-06-02 13:45
@SounD120 I tried to reinstall cordova tools and restart VSCode - didn't work.

Here is a sample of an quasar vuejs app.
https://drive.google.com/file/d/1dIXV4a_7lzUAxPdFFFVBWodD7urTULtS/view?usp=sharing

* Once you will open it do
 `npm install`
* Then I go to scr-cordova folder:
`cd src-cordova`
* Then I build an app with:
* `quasar build -m cordova -T android`

Scenario #1

I connect my android device with USB cable and run it with:
`cordova run android`

An app successfully installed on device and run (I can see it on device).
Then I go to debugger and try to "Attach to running android on device", I got nothing in debug console and the is the look of VSCode:
<img width="1440" alt="Screenshot 2020-06-02 at 08 36 41" src="https://user-images.githubusercontent.com/19554725/83526999-d26e5e00-a4ac-11ea-8918-74eb4d5f3ec1.png">

Scenario #2 

I connect my android device with USB cable, go to debugger and "Run Android on device", the result is error:

`[cordova-tools] Error processing "launch": Current working directory doesn't contain a Cordova project. Please open a Cordova project as a workspace root and try again.`

<img width="1440" alt="Screenshot 2020-06-02 at 08 37 11" src="https://user-images.githubusercontent.com/19554725/83527012-d8fcd580-a4ac-11ea-94b0-20d9461b4a2a.png">

Launch.json settings I haven't touched

<img width="1440" alt="Screenshot 2020-06-02 at 08 43 33" src="https://user-images.githubusercontent.com/19554725/83527311-401a8a00-a4ad-11ea-9c40-617ddf66b5be.png">

**Comment by JiglioNero** [comment] 2020-06-03 11:20
Hello @AEiosApp , unfortunately we could not download the application, because access to this file is limited. Please share your demo application. For example you can share it as a Github repo.

**Comment by AEiosApp** [comment] 2020-06-03 13:24
Sorry, just changed sharing settings, please try now the same link

**Comment by JiglioNero** [comment] 2020-06-05 10:29
@AEiosApp, extension works only from folders with Сordova projects, so the root folder should be the Сordova folder and `.vscode/launch.json` should be directly in it.
Open the `src-cordova` folder with VS Сode, create `launch.json` for Сordova there, in which case the scripts will work.

**Comment by AEiosApp** [comment] 2020-06-05 14:01
Hi, thanks for suggestion, so what I did:

#1. Copied launch.json from vuejs project root `.vscode` to `src-cordova/.vscode`

<img width="716" alt="Screenshot 2020-06-05 at 08 54 38" src="https://user-images.githubusercontent.com/19554725/83884443-815ba580-a70a-11ea-9834-28b397522170.png">

#2. Opened in VS code not Vuejs root project folder, but `src-cordova`
(it is a kind of inconvenient, because with Vuejs+cordova project I have to work with a project root folder, but for debugging have to reopen src-cordova folder as a workspace)

#3. Finally I tried to Run android on device or Attach android on device, but I was faced a new error.

Any suggestions?

<img width="1440" alt="Screenshot 2020-06-05 at 08 54 01" src="https://user-images.githubusercontent.com/19554725/83884697-e4e5d300-a70a-11ea-99dd-5189173fe464.png">

**Comment by AEiosApp** [comment] 2020-06-05 14:51
Finally made it working:

#1. I've added to `.bash_profile` following paths:
```
export ANDROID_HOME=$HOME/Library/Android/sdk
export ANDROID_SDK_ROOT=$HOME/Library/Android/sdk
export PATH=$PATH:$ANDROID_HOME/emulator
export PATH=$PATH:$ANDROID_HOME/tools
export PATH=$PATH:$ANDROID_HOME/tools/bin
export PATH=$PATH:$ANDROID_HOME/platform-tools
```

#2. To be able to work and run debugger from the Vuejs root workspace, in my root `.vscode/launch.json` I've changed parameter `"cwd": "${workspaceFolder}/src-cordova"`

<img width="879" alt="Screenshot 2020-06-05 at 09 50 29" src="https://user-images.githubusercontent.com/19554725/83890906-06968880-a712-11ea-96ab-d11087c49363.png">

**Closed** 2020-06-08 08:00 UTC
Labels: waiting-for-clarification
