### ISSUE TITLE
Launch command from local modules (lack of documentation)

### ISSUE THREAD

**Issue by Takkuz** [microsoft/vscode-cordova#498] opened 2019-02-05 16:51 UTC
Developing many different project could resolve on vary different Cordova and Ionic version installed, so it's very useful to have it installed locally and runned throught npm scripts. But it's not working with this plugin.

## Actual Behavior
1. Installing `ionic` and `cordova` as local dependencies (without `-g` flag)
2. Trying to run "On device", or anything else, won't work because of `spawn ionic ENOENT`

## Expected Behavior
- Looking for executable binaries on local `./node_modules/.bin` before looking into PATH
- Let user define position of executable per project basis or globally but with relative path

## Software versions
- Cordova VS Code extension version: 1.7.0
- VSCode version: 1.30.2
- OS platform and version: Ubuntu 18.10
- NodeJS version: 10.15.0
- Cordova version: 8.1.2

**Comment by ruslan-bikkinin** [comment] 2019-02-06 09:31
Hi @Takkuz and thanks for reaching us. We already have `cordovaExecutable` parameter for `launch.json`: set it to `node_modules/.bin/ionic` if your project is Ionic one or to `node_modules/.bin/cordova` if your project is just a Cordova one. 

Please let us know if it helps you.

**Comment by Takkuz** [comment] 2019-02-06 15:38
It works like a charm... Thank you! My issue now should be "feature `cordovaExecutable` needs to be documented". :D

**Comment by ruslan-bikkinin** [comment] 2019-02-06 19:59
@Takkuz absolutely agree :+1: I'll keep it open until docs is updated.

**Comment by gaspachoandalus** [comment] 2019-02-08 10:17
Hi,
I'm using Windows 10, VS Code extension version 1.7.0, VSCode 1.31
I also have `ionic` and `cordova `as local dependencies, so I tested this `cordovaExecutable` feature.

### case 1
With `"cordovaExecutable": "node_modules/.bin/cordova"`
The output is
`spawn node_modules/.bin/cordova ENOENT`

### case 2
With `"cordovaExecutable": "node_modules\\.bin\\cordova.cmd"`
The output is
```
(node:30504) UnhandledPromiseRejectionWarning: CordovaError: Cordova does not know cordova; try `cordova help` for a list of all the available commands
[....]
```
Looks like there's an extra "cordova" which has been added by the extension

### case 3
With `"cordovaExecutable": "node_modules\\.bin\\ionic.cmd"`
The output is
```
[...]
> cordova run android --device
'cordova' is not recognized as an internal or external command [...]
[ERROR] The Cordova CLI was not found on your PATH. Please install Cordova globally:
        npm i -g cordova
[...]
'node_modules\.bin\ionic.cmd cordova run android --device --verbose --no-interactive' failed with exit code 1

```
### case 4
Finally I used `"cordovaExecutable": "npx.cmd"`
And the app builds with cordova and starts correctly on my phone.
However it's not possible to build via ionic.

**Comment by RedMickey** [comment] 2021-07-22 09:51
Hi @gaspachoandalus, I tested `cordovaExecutable` parameter usage on Windows 10 (VS Code v1.58.2, Cordova Tools v2.2.3) and could successfully run Cordova and Ionic applications via the extension. Below are my reproducing steps:
- Cordova project
    - Added `cordova` package to dev dependencies using `npm i cordova --save-dev`
    - Added `"cordovaExecutable": ".\\node_modules\\.bin\\cordova.cmd"` parameter to a debugging configuration
    - Ran the debugging configuration, the application launched without problems
- Ionic project
    - Added `cordova` and `@ionic/cli` packages to dev dependencies using `npm i cordova @ionic/cli --save-dev`. Installation of `cordova` package is required to avoid the error message below, since Ionic CLI uses `cordova` commands internally.
    ```
    [...]
    > cordova build android --emulator --verbose --target emulator-5554
    'cordova' is not recognized as an internal or external command, operable program or batch file.
    [ERROR] The Cordova CLI was not found on your PATH. Please install Cordova globally:
        npm i -g cordova
    [...]
    .\node_modules\.bin\ionic.cmd cordova run android --verbose --emulator --target=emulator-5554 --no-interactive failed with exit code 1
    ```
    - Added `"cordovaExecutable": ".\\node_modules\\.bin\\ionic.cmd"` parameter to a debugging configuration
    - Ran the debugging configuration, the application launched without problems

If this issue is still relevant for you, could you please test `cordovaExecutable` parameter usage on the latest version of the extension to check whether it works correctly for you?
Please let us know about your results.

**Comment by RedMickey** [comment] 2021-07-29 12:16
We've updated the extension documentation for debugging scenarios parameters. I'm closing this issue.

**Closed by RedMickey** 2021-07-29 12:16 UTC
Labels: documentation
