### ISSUE TITLE
Cordova platform and plugin intellisense not enabled by default

### ISSUE THREAD

**Issue by MSLaguana** [Microsoft/vscode-cordova#59] opened 2016-03-14 20:06 UTC
Due to a bug in vscode, projects will not pick up typings for cordova intellisense by default. See https://github.com/Microsoft/vscode/issues/3936 for more details, but a workaround is to add a `jsconfig.json` file in the root of the project which is valid json. At minimum it can be `{}`.

**Comment by egamma** [comment] 2016-03-14 20:49
@MSLaguana The currenct behaviour is by design and consistent with typescript and its tsconfig.json. When you have no jsconfig.json/tsconfig.json then each file in the project is treated as an island. Since there is no reference to the cordova typings from a file, these typings will not be found. You can add such a reference by using a /// reference to the corresponding .d.ts file.

In VS Code 0.10.8 we used a different behaviour and when you have no jsconfig.json we treated all files inside the folder to belong to the project. Now that Salsa comes from TypeScript you get the same behaviour as in typescript.

**Comment by MSLaguana** [comment] 2016-03-14 21:00
In that case we'll have to drop in a jsconfig to enable our typings.

**Comment by hamiltonia** [comment] 2016-03-16 18:04
Fix checked in, will be in the next extension update.

**Closed by hamiltonia** 2016-03-16 18:04 UTC
Labels: bug
