### ISSUE TITLE
Livereload not working for "simulate android in browser" for Ionic 4+ projects

### ISSUE THREAD

**Issue by timkovik** [microsoft/vscode-cordova#606] opened 2020-03-24 00:19 UTC
Live reload is not working when enabled in the config, using the "livereload": true configuration.

## launch.json
```
{
      "name": "Simulate Android in browser",
      "type": "cordova",
      "request": "launch",
      "platform": "android",
      "target": "chrome",
      "simulatePort": 8000,
      "livereload": true,
      "sourceMaps": true,
      "cwd": "${workspaceFolder}",
      "ionicLiveReload": true,
      "devServerAddress": "localhost",
      "devServerPort": 8100,
      "forceprepare": true,
    }
```
2. Software versions
- Cordova VS Code extension version: 1.9.3
- VSCode version:  1.43.1
- OS platform and version: Macos Catalina 10.15.3
- NodeJS version: 12.16.1
- Cordova version: 9.0.0 (cordova-lib@9.0.1)
- Cordova-Android version: android 8.1.0

**Comment by SounD120** [comment] 2020-03-24 10:09
Hi @timkovik and thanks for reaching us. I tried to reproduce this, but in my case it doesn't reproduce. I created new Cordova app, ran Simulate and then changed js and html code in runtime and the changes has been applied to the simulation in live mode. Does your app use pure Cordova or Ionic? Also, could you please describe what changes you make to the code that don't work with `livereload`?

**Comment by SounD120** [comment] 2020-03-30 10:14
@timkovik Just a friendly ping on this.

**Comment by iamkarlson** [comment] 2020-03-30 20:48
@SounD120 my app is using ionic and the same problem. I found that if I manually rebuild the app from command line then livereload works. Are there any tips on how to check that watch job is actually working? it must be essential for livereload stuff.

**Comment by SounD120** [comment] 2020-03-31 07:51
Hi @iamkarlson this is a known issue of Ionic 4+ caused by [absence of special `--watch` flag for `ionic-cli`](https://github.com/ionic-team/ionic-cli/issues/3999). As soon as this flag will be added this feature will be fixed for that case.

**Comment by SounD120** [comment] 2020-04-01 07:28
@timkovik Is your case similar to the @iamkarlson case?

**Comment by iamkarlson** [comment] 2020-04-02 19:32
@SounD120 thanks for explanation! Is there any snippet how to run watch task in the background? it would give users opportunity to overcome the issue without waiting ionic to solve that

**Comment by SounD120** [comment] 2020-04-13 09:08
Hi @iamkarlson , sorry for the late response. The issue that I have sent to you is about Cordova Simulate debug scenarios only, so it should not affect the other scenarios. Also, please keep in mind that for Ionic there is the `ionicLiveReload` debug scenario argument instead of `livereload` for pure Cordova.

Could you please send us the exact debug scenario (chunk from `launch.json` file) from which you are trying to launch your Ionic application and the exact Ionic framework version you use?

**Closed** 2022-06-21 16:57 UTC
Labels: known-issue, external-report, simulate
