### ISSUE TITLE
[Issue] [Cordova Tool] Unable to debug with error: "Path must be string. Received null" after upgrade VS Code from 0.10.9 to 0.1010

### ISSUE THREAD

**Issue by saravmajestic** [Microsoft/vscode-cordova#48] opened 2016-03-06 12:28 UTC
I am getting the error `[cordova-debug-adapter] TypeError: Path must be string. Received null` when trying to debug my phonegap app using "Cordova tools".
Steps:

Installed VSCode Version 0.10.9 (0.10.9)
installed cordova extension from extensions gallery
selected Cordova from debug configuration and used default `launch.json`
clicked 'Run Android on emulator' Got the error as above.

I tried to add the workaround as mentioned in [https://github.com/Microsoft/vscode/issues/3625](https://github.com/Microsoft/vscode/issues/3625)
I tried to set sourceMaps as false and "outDir": "${workspaceRoot}" , but still getting same error.

I don't know which sourcemaps I have to specify as mentioned in the workaround. I am using Mac 10.10.5

Screenshot as below:
<img width="1440" alt="screen shot 2016-03-06 at 5 46 28 pm" src="https://cloud.githubusercontent.com/assets/1147025/13554046/88eb3df6-e3c3-11e5-8a56-55f1487ba433.png">

**Comment by DickvdBrink** [comment] 2016-03-07 08:49
Same issue here (with the insider build)

**Comment by MSLaguana** [comment] 2016-03-07 16:11
What version of node do you have installed? Looks like this might be to do with a change in node 5.7

**Comment by saravmajestic** [comment] 2016-03-07 16:13
My Node version is pretty old 0.10.32. Should I upgrade to latest?

**Comment by MSLaguana** [comment] 2016-03-07 16:16
That is quite old, but shouldn't be related to this particular issue then. I'll investigate further.

**Comment by digeff** [comment] 2016-03-07 16:22
@saravmajestic Could you please try:
1. Setting sourceMaps: false and deleting the outDir key
2. Setting sourceMaps: true and "outDir": "${workspaceRoot}"
3. Setting sourceMaps: true and "outDir": "${workspaceRoot}/www" or whatever is the path to your index.html

**Comment by saravmajestic** [comment] 2016-03-07 17:12
@digeff I tried all these combinations now and still getting the error.

My phonegap version is 5.3.9. I will try to generate a new cordova project and try this out. In the meantime, let me know if you guys have any other work around

**Comment by MSLaguana** [comment] 2016-03-07 17:24
For a workaround, you should be able to specify `"sourceRoot": "${workspaceRoot}/www"` I believe. If that does fix it, please let us know and we'll put in a proper fix.

**Comment by MSLaguana** [comment] 2016-03-07 18:41
Looks like I may have been mistaken, and that value comes from the webview running the app, not from the launch.json.

I still haven't been able to reproduce the issue locally, but if you are willing to help us debug I can walk you through adding some extra logging so we can track down where the issue is:

1. Go to `~/.vscode/extensions/vsmobile.cordova-tools-1.0.3/out/debugger`, and then make some changes to `adapter/sourceMaps/pathUtilities.js` and `adapter/sourceMaps/sourceMaps.js`. After `var Path = require('path');` add the following:
  
  ```
function isAbs(s) {
      console.info(new Error().stack);
      console.info(s);
      return Path.isAbsolute(s);
}
  ```
2. In those files, find and replace `Path.isAbsolute` with `isAbs`
3. Go to `webkit/utilities.js` and make a similar change, but use `path.isAbsolute` instead of `Path.isAbsolute`
4. go back to `~/.vscode/extensions/vsmobile.cordova-tools-1.0.3/out/src/debugger` and run `node debugCordova.js --server=9955`. This will run the debug adapter in server mode, and you'll be able to see its console output.
5. Open up your project in vscode, and in your launch.json at the top level add `"debugServer": 9955,`
6. Try to launch your project and trigger the bug
7. Include any relevant output from the debug adapter we ran in step 4

I suspect that it is these `isAbsolute` calls that are causing the issue, but if not we still may get some useful output from the console.

**Comment by saravmajestic** [comment] 2016-03-08 04:32
@MSLaguana , thanks for detailed steps. I have tried to run debug server and I got this below error:

`node debugCordova.js --server=9955
waiting for v8 protocol on port 9955
>> accepted connection from client

/Users/saravanan/.vscode/extensions/vsmobile.cordova-tools-1.0.3/out/debugger/common/v8Protocol.js:52
        this._pendingRequests = new Map();
                                    ^
ReferenceError: Map is not defined
    at CordovaDebugSession.V8Protocol (/Users/saravanan/.vscode/extensions/vsmobile.cordova-tools-1.0.3/out/debugger/common/v8Protocol.js:52:37)`

Since my node version is old, Map is not available yet. I will see if I can inject it somehow and check.

**Comment by MSLaguana** [comment] 2016-03-08 04:56
I should have realized this would happen after you mentioned your older node version. If you could try to get node 4.X and use that, it should match what vscode uses more closely. If you don't want to update node system wide, you could consider [nvm](https://github.com/creationix/nvm) for managing multiple versions of node, or you could download the standalone binaries at https://nodejs.org/dist/v4.3.2/node-v4.3.2-darwin-x64.tar.gz and directly reference the node binary from that.

**Comment by saravmajestic** [comment] 2016-03-08 07:45
@MSLaguana , thanks for the tips

I tried these workarounds:
- installed nvm and installed node 5.7.1, made this version as default using this command `nvm alias default 5.7.1`
- Ran my existing project, without any changes you mentioned above with fresh version of cordova tools. Got the same error :(
- Ran again with the changes you mentioned, I didnt get any logs while running. It just said 'process exit. Not for server instance' :(
- created new cordova project and added android platform. Tried to run the debugger for 'Run Android device' and 'Run Android on emulator'. Still error :(

Is there anything else I can do to get some more logs?

**Comment by burtonsmith** [comment] 2016-03-08 13:40
I am also having the same problem. I was using it previously without an issue, but it started after I installed the latest update for VS Code yesterday.

**Comment by DickvdBrink** [comment] 2016-03-08 14:31
I added some logging with the steps above: This is the result:
```
workspaceRoot: undefined
{ '0': undefined, '1': 'config.xml' }
Error
    at Object.path.join (C:\Users\dvdbrink\.vscode\extensions\vsmobile.cordova-tools-1.0.1\out\src\debugger\debugCordova.js:11:22)
    at Object.path.join (C:\Users\dvdbrink\.vscode\extensions\vsmobile.cordova-tools-1.0.1\out\src\debugger\cordovaDebugAdapter.js:17:21)
    at Object.path.join (C:\Users\dvdbrink\.vscode\extensions\vsmobile.cordova-tools-1.0.1\out\src\debugger\cordovaIosDeviceLauncher.js:14:21)
    at Object.path.join (C:\Users\dvdbrink\.vscode\extensions\vsmobile.cordova-tools-1.0.1\out\debugger\webkit\utilities.js:19:21)
    at Object.path.join (C:\Users\dvdbrink\.vscode\extensions\vsmobile.cordova-tools-1.0.1\out\src\utils\cordovaProjectHelper.js:8:21)
    at Object.path.join (C:\Users\dvdbrink\.vscode\extensions\vsmobile.cordova-tools-1.0.1\out\src\utils\telemetry.js:26:21)
    at Object.path.join (C:\Users\dvdbrink\.vscode\extensions\vsmobile.cordova-tools-1.0.1\out\src\debugger\cordovaPathTransformer.js:10:21)
    at Object.Path.join (C:\Users\dvdbrink\.vscode\extensions\vsmobile.cordova-tools-1.0.1\out\debugger\adapter\sourceMaps\sourceMaps.js:15:21)
    at Object.Path.join (C:\Users\dvdbrink\.vscode\extensions\vsmobile.cordova-tools-1.0.1\out\debugger\adapter\sourceMaps\pathUtilities.js:12:21)
    at Function.CordovaProjectHelper.getCordovaProjectRoot (C:\Users\dvdbrink\.vscode\extensions\vsmobile.cordova-tools-1.0.1\out\src\utils\cordovaProjectHelper.js:88:54)
```

In the CordovaDebugAdapter.prototype.launch [link](https://github.com/Microsoft/vscode-cordova/blob/4439865650b94f8701e5645294af71aa29855ed2/src/debugger/cordovaDebugAdapter.ts#L35) the `launchArgs.cwd` is empty which is causing the crash

**Comment by burtonsmith** [comment] 2016-03-08 14:53
Where did you add it exactly? I have a presentation on this this afternoon and would love to have this working.

**Comment by DickvdBrink** [comment] 2016-03-08 14:57
@burtonsmith in the `launch.json` you have the configurations section. You need to add them to all of them but below you can find the first two examples
```
{
	"version": "0.2.0",
	"configurations": [
		{
			"name": "Run Android on device",
"cwd": "${cwd}",
			"type": "cordova",
			"request": "launch",
			"platform": "android",
			"target": "device",
			"port": 9222,
			"sourceMaps": true
		},
		{
			"name": "Run iOS on device",
			"type": "cordova",
"cwd": "${cwd}",
			"request": "launch",
			"platform": "ios",
			"target": "device",
			"port": 9220,
			"sourceMaps": true
		},
```
I did align them on the left on purpose so you could see :)

**Comment by burtonsmith** [comment] 2016-03-08 15:00
You, sir, are awesome! Thank you @DickvdBrink! This is a great workaround.

**Comment by saravmajestic** [comment] 2016-03-08 15:02
@DickvdBrink awesome. This is working now. Thanks a lot!

**Comment by DickvdBrink** [comment] 2016-03-08 15:04
I might create a PR with a fix tonight if @MSLaguana doesn't beat me to it :)

**Comment by Shreyash23** [comment] 2016-03-08 16:30
Had the same problem, adding
"cwd": "${cwd}"
into all the configurations fixed it.

Thanks @DickvdBrink .
Cheers

**Comment by MSLaguana** [comment] 2016-03-08 17:24
Thanks a lot for investigating @DickvdBrink ! It seems that in the latest vscode the contract with debug adapters changed. I'll create a fix for new projects, but for anyone hitting this issue, the fix is as above: adding `"cwd": "${workspaceRoot}"` or similar to all your cordova launch configurations in launch.json

**Comment by MSLaguana** [comment] 2016-03-08 17:36
This will be fixed for new projects in the next release, until then I'll leave this issue open so anyone else hitting it can find it easily.

**Comment by MShamiltonia** [comment] 2016-03-09 00:31
A new version of the extension was pushed to the marketplace which addresses this issue. After updating the extension existing projects will need to either include cwd attribute for each configuration as described previously (`"cwd": "${workspaceRoot}"`) or delete the generated launch.json (if you haven't modified it) so that it can be regenerated correctly.

**Closed** 2016-03-09 19:01 UTC
Labels: bug

**Comment by jagansai** [comment] 2016-04-09 04:21
I still get the error even with the latest launch.json file.

**Comment by aualdrich** [comment] 2016-08-29 18:09
Note I got this error when I deleted the contents of the android and ios folders but left the root "android" and "ios" platform folders intact. Deleting the actual folders fixed it.
