### ISSUE TITLE
Unable to find localabstract name of cordova app

### ISSUE THREAD

**Issue by erenozm** [Microsoft/vscode-cordova#215] opened 2016-12-09 12:01 UTC
after the latest update, i keep getting this error on "Run Android on device" option.

`Unable to find localabstract name of cordova app`

here is the launch.json file:

```
{
            "name": "Run Android on device",
            "type": "cordova",
            "request": "launch",
            "platform": "android",
            "target": "device",
            "port": 9222,
            "sourceMaps": true,
            "cwd": "${workspaceRoot}",
            "ionicLiveReload": false
        }
```

any help?

thanks

**Comment by arnaudauroux** [comment] 2016-12-09 15:16
I have the same issue here with the last update.
Error: [cordova-debug-adapter] Error: Unable to find localabstract name of cordova app

**Comment by MSLaguana** [comment] 2016-12-09 17:58
I don't see this happen when I try it out.

Can you please try following these steps: Connect your device, and start the app on the device manually. Then open up a command line with access to `adb` and run the following:

* `adb devices`, and take note of the name of the device. E.g. if the result was
  `169.254.76.233:5555     device` then the name is `169.2454.76.233:5555`
* `adb -s DEVICENAME shell ps`, e.g. `adb -s 169.254.76.233:5555 shell ps`. In that output, look for the name of your app, e.g. if my app is `io.cordova.hellocordova` I look for a line like `u0_a53    1309  161   1531940 70604 futex_wait b733c1e2 S io.cordova.hellocordova`. Take note of the second value, in my case `1309`. That's the PID of the running app.
* `adb -s DEVICENAME shell cat /proc/net/unix` and look for an entry ending with `@webview_devtools_remote_PID`, e.g. I had `00000000: 00000003 00000000 00000000 0001 03 13781 @webview_devtools_remote_1309`.
* `adb -s DEVICENAME shell ls -l /proc/PID/fd` and see if the last number of the previous command's line appears as  as `socket:[NUMBER]`, e.g. `lrwx------ u0_a53   u0_a53            2016-12-09 09:37 97 -> socket:[13781]`

There are some other things I'd like to validate about this process, but if you could respond with your versions of the example lines I give above, or places where you can't find them, that'd help track down what is happening here.

**Comment by erenozm** [comment] 2016-12-09 18:15
hello @MSLaguana  
i found this entry:
`00000000: 00000002 00000000 00010000 0001 01 2622685 @webview_devtools_remote_22000`

but i got this error for the last command:

```
C:\Users\***\AppData\Local\Android\sdk\platform-tools>adb -s DEVICENAME shell ls -l /proc/PID/fd
/proc/PID/fd: No such file or directory
```

**Comment by MSLaguana** [comment] 2016-12-09 18:21
Where I said `PID` I meant to replace it with the process ID from the second step. In my case, I looked at `/proc/1309/fd`

**Comment by erenozm** [comment] 2016-12-09 18:30
sorry for misunderstanding. 

```
C:\Users\***\AppData\Local\Android\sdk\platform-tools>adb -s DEVICENAME  shell ls -l /proc/22000/fd
opendir failed, Permission denied
```

**Comment by MSLaguana** [comment] 2016-12-09 18:32
Interesting. That is most likely what is causing us to fail then. What is your device, and what version of android is it running?

**Comment by erenozm** [comment] 2016-12-09 18:43
it's Samsung Galaxy Note 4 Android 6.0.1
I also tried on a tablet PMT5001_3G Android 4.4.2 same error.

**Comment by lucascarlos** [comment] 2016-12-09 18:44
I have the same problem of @erenozm 

Followed @MSLaguana instructions and also got:

`opendir failed, Permission denied`

Device:
Samsung Galaxy J3 (2016)
Model SM-J320M
Android 5.1.1

**Comment by erenozm** [comment] 2016-12-09 18:57
just tried on a Samsung 10.1 2014 Edition Android 5.1.1 same error.

**Comment by MSLaguana** [comment] 2016-12-09 18:58
Thanks for the confirmation. I'll try some more devices out and see what turns up. In the short term, there's something that may work as a temporary fix: Go to the extension folder, either `~/.vscode/extensions/vsmobile.cordova-tools-1.2.4` or `C:\Users\USERNAME\.vscode\extensions\vsmobile.cordova-tools-1.2.4`, then open up `out/src/debugger/cordovaDebugAdapter.js`.

Go to line 224 and delete lines 224-232 (which is the code that tries to run `ls -l /proc/PID/fd`), then look for the line `if (socketsInodes.indexOf(...` and replace the condition with `pathField.indexOf(pid) === -1`

If you are not using crosswalk then I believe it should be able to find the correct value without reading that folder, but I haven't tested it out thoroughly yet so there may be issues.

**Comment by MSLaguana** [comment] 2016-12-09 19:14
Looks like the difference is that these devices (including one I have on hand, I've replicated the issue) don't grant read permissions to the `/fd` folder. We'll have to change the heuristics we use to find the debugging socket to not rely on that.

**Comment by erenozm** [comment] 2016-12-09 19:39
thank you @MSLaguana. it is working for now. i got the console logs back, but i needed to repeat https://github.com/Microsoft/vscode-cordova/issues/201#issuecomment-257056099

**Comment by lucascarlos** [comment] 2016-12-09 19:40
The sugested temporary fix worked!

I could debug on device hiting the breakpoints on source files.

Test enviroment:

VS Code 1.7.2
Cordova Tools Extension 1.2.4
Ionic 2 Project
Samsung Galaxy J3 (2016)
Android 5.1.1

launch.json
`{
            "name": "Run Android on device",
            "type": "cordova",
            "request": "launch",
            "platform": "android",
            "target": "device",
            "port": 9222,
            "sourceMaps": true,
            "cwd": "${workspaceRoot}",
            "ionicLiveReload": false
}`

Thank you very much!

**Comment by arnaudauroux** [comment] 2016-12-12 10:37
The workaround does not work for me. Since the update of the cordovaDebugAdapter file, i have the following error : [cordova-debug-adapter] Error: Cannot connect to the target: read ECONNRESET.
The listing of the /proc/PID/fd folder failed alors with a 'permission denied' error.

**Comment by arnaudauroux** [comment] 2016-12-12 12:53
Ok i simply did reboot and now the workaround works for me too.

Thank you @MSLaguana

**Comment by sahildaga95** [comment] 2016-12-13 06:08
@MSLaguana followed your steps:-
Getting the following error now
LAUNCH SUCCESS
No scripts found for hook "after_run".
App successfully launched
Attaching to android
pid is not defined

on line 253 after deletion i changed
` if (socketsInodes.indexOf(pathField.indexOf(pid) === -1)) {
                                        continue;
                                    }`

**Comment by arnaudauroux** [comment] 2016-12-13 09:45
@sahildaga95 the change you applied on line 253 is not the good one, here is it: 
if (pathField.indexOf(pid) === -1) { continue; }

**Comment by sahildaga95** [comment] 2016-12-13 09:56
@arnaudauroux - Oops My Bad ! 
Your code did the trick. Thank You

**Comment by KinsonDigital** [comment] 2016-12-14 05:00
This also worked for me as well!!  I have been working on this issue for over 10 hours.  Thank you so much.  Do you have an idea when this will be fixed and have an update released?

Thanks again arnaudauroux.

**Comment by KinsonDigital** [comment] 2016-12-19 16:11
Just curious.  Is this a fix that will be rolled out anytime soon?

**Comment by victorsosa** [comment] 2016-12-27 12:55
@MSLaguana I follow you instructions and everything seems like you said and working as expected, but still getting the original message error:
Unable to find localabstract name of cordova app

ENV info:
VS Code 1.8.1
Cordova Tools Extension 1.2.4
Ionic 1 Project
Android >4.2

> I don't see this happen when I try it out.
> 
> Can you please try following these steps: Connect your device, and start the app on the device manually. Then open up a command line with access to adb and run the following:
> 
>     adb devices, and take note of the name of the device. E.g. if the result was
>     169.254.76.233:5555 device then the name is 169.2454.76.233:5555
>     adb -s DEVICENAME shell ps, e.g. adb -s 169.254.76.233:5555 shell ps. In that output, look for the name of your app, e.g. if my app is io.cordova.hellocordova I look for a line like u0_a53 1309 161 1531940 70604 futex_wait b733c1e2 S io.cordova.hellocordova. Take note of the second value, in my case 1309. That's the PID of the running app.
>     adb -s DEVICENAME shell cat /proc/net/unix and look for an entry ending with @webview_devtools_remote_PID, e.g. I had 00000000: 00000003 00000000 00000000 0001 03 13781 @webview_devtools_remote_1309.
>     adb -s DEVICENAME shell ls -l /proc/PID/fd and see if the last number of the previous command's line appears as as socket:[NUMBER], e.g. lrwx------ u0_a53 u0_a53 2016-12-09 09:37 97 -> socket:[13781]
> 
> There are some other things I'd like to validate about this process, but if you could respond with your versions of the example lines I give above, or places where you can't find them, that'd help track down what is happening here.

**Comment by MSLaguana** [comment] 2016-12-28 21:52
This should be fixed in the latest version now.

**Comment by bradwyoung** [comment] 2016-12-28 23:41
@MSLaguana getting same error.  Just installed 1.8.1 and Cordova Tools 1.2.5.  I looked for the code mentioned above to remove but it does not appear to be in the cordovaDebugAdapter.js file. 

"Unable to find localabstract name of cordova app"

Any ideas?  Can I roll back to the older version?

**Comment by bradwyoung** [comment] 2016-12-29 00:11
I had Cordova Tools 1.2.4 on my laptop with code mentioned above already removed.  I copied that back over to my desktop and it works.

**Comment by MSLaguana** [comment] 2016-12-29 17:19
I've just double checked, and not had this issue on a device. Can you please try the first three steps mentioned in https://github.com/Microsoft/vscode-cordova/issues/215#issuecomment-266078890 so we can see what the underlying issue is?

**Comment by bradwyoung** [comment] 2016-12-29 18:28
Output from the 3rd step.

0000000000000000: 00000002 00000000 00010000 0001 01 1398393 @webview_devtools_remote_21330

Hopefully this helps.  Let me know if you need anything else.

**Comment by MSLaguana** [comment] 2016-12-29 18:56
And just to be sure, your process' PID was `21330`? If so, I would expect the code to work for you.

Could you please go to `cordovaDebugAdapter.js` line 244 in the 1.2.5 version and just before `if (pathField === "@webview_...` add in `_this.outputLogger("Considering line: " + line);, _this.outputLogger("PID = " + pid);` so we can try and see why it is failing.

**Comment by bradwyoung** [comment] 2017-01-02 04:06
Well, upgraded to 1.2.5 again and it works now.  Don't know what I did differently, other than I upgraded VS Code then the extension last time.  This time I was already on latest VS Code so just upgraded the extension.  Looks like it is working.

**Comment by victorsosa** [comment] 2017-01-02 11:50
I just upgraded to 1.2.5 and still getting "Unable to find localabstract name of cordova app" message

**Comment by bradwyoung** [comment] 2017-01-03 02:38
Well, having the issue again.  I removed my android platform and re-added and this is the first time I have tried to debug since then.  i added the code you requested to the 'cordovaDebugAdapter.js' and here is the output.

```
Considering line: 0000000000000000: 00000002 00000000 00010000 0001 01 156133 @sbrowser_devtools_remote

PID = undefined
Considering line: 0000000000000000: 00000002 00000000 00010000 0001 01 156133 @sbrowser_devtools_remote

PID = undefined
Considering line: 0000000000000000: 00000002 00000000 00010000 0001 01 156133 @sbrowser_devtools_remote

PID = undefined
Considering line: 0000000000000000: 00000002 00000000 00010000 0001 01 156133 @sbrowser_devtools_remote

PID = undefined
Considering line: 0000000000000000: 00000002 00000000 00010000 0001 01 156133 @sbrowser_devtools_remote

PID = undefined
```

**Comment by MSLaguana** [comment] 2017-01-03 03:45
Ah, that would explain it. You have `@sbrowser_devtools_remote` where we expect either `@devtools_remote_PID` or `@PACKAGEID_devtools_remote`. What plugins are you using in your app?

**Comment by bradwyoung** [comment] 2017-01-03 14:49
So, can I change this somehow?  I don't remember configuring this originally.

Here are the the plugins.

cordova-plugin-geolocation
cordova-plugin-whitelist
cordova-plugin-splashscreen
cordova-plugin-inappbrowser
cordova-plugin-device
cordova-plugin-inapppurchase
cordova-plugin-ios-non-exempt-encryption
cordova-plugin-app-version
cordova-plugin-camera
phonegap-plugin-barcodescanner
cordova-plugin-code-push

**Comment by MSLaguana** [comment] 2017-01-03 17:43
After looking closer I see that actually the `sbrowser` is probably a different app that you have installed, and we're just not finding the app. Since it is also reporting that the `PID = undefined` that seems to suggest that we don't believe that the app is running. Can you please verify that the app is running on the device when we fail to attach? And once we've failed to attach, can you re-run the `ps` command to see if you can find the app, and the `cat /proc/net/unix` command to see what entries reference `_devtools_remote`.

**Comment by jimwhitelaw** [comment] 2017-01-04 03:55
I encountered this issue today, trying to attach to the emulator. Using the info above to output the lines being considered (at line 239 of cordovaDebugAdapter.js), I found this:

`Considering line: 00000000: 00000002 00000000 00010000 0001 01  5448 @webview_devtools_remote_2804`

What isn't immediately obvious is that there are two spaces between fields '01' and '5448'. That was causing the line to be parsed as having 8 fields, not 7, with one of them being empty and fields[7] containing '5448' instead of '@webview_devtools_remote_2804'

I fixed this by changing line 229 which parses the line from:

`var fields = line.split(/[ \r/);`

to

`var fields = line.split(/\s+/);`

The correct pid is now found and the debugger attaches properly.

**Comment by bradwyoung** [comment] 2017-01-06 04:06
Well, looks like I was having a different issue.  VS Code was not launching the app when I was trying to debug the app using the 'Run Android on device'.  So when I closed the app even the old 1.2.4 version of the extension code was not working.  I tracked down the issue to be missing icon and splash screen resources from where I had removed the platform and re-added.  1.2.5 now is working for me.

**Comment by victorsosa** [comment] 2017-01-16 21:32
I just upgraded to 1.2.6 and It WORKING NOW 👍

**Comment by akmarneko** [comment] 2017-01-26 06:52
@MSLaguana , i have install the latest 1.2.6... still not working..
i have try to remove the platform, re-add, reboot my laptop...
i have follow all the instruction above.. but still cant debug correctly.
the apps was install but then debug console prompt the error below and stop debug.

------
LAUNCH SUCCESS
No scripts found for hook "after_run".
App successfully launched
Attaching to android
Unable to find localabstract name of cordova app

**Comment by MSLaguana** [comment] 2017-01-26 17:14
@akmarneko Are you targeting an emulator or a device? Does your app look like it starts, or does it not launch?

**Comment by akmarneko** [comment] 2017-01-27 00:58
@MSLaguana  i'm targeting on device.
The apps was launch, show my login in screen then it stop. 
the error was : 

> App successfully launched
> Attaching to android
> Unable to find localabstract name of cordova app


FYI, problem solve.. the previous issues occur on Android 4.1.2
but after i using android Devices 6.1.1 then it run smoothly.

Thanks!

**Comment by MSLaguana** [comment] 2017-01-27 18:24
That would indeed explain it, prior to android 4.4 or so the webview has some significant behavior changes.

**Comment by sgadekar81** [comment] 2017-02-04 10:59
was facing the same issue, the problem in my case was JAVA_HOME and PATH variable was pointing to jdk1.7.0_79, changed jdk1.7.0_79 to jdk1.8.0_121 and it worked for me

**Closed** 2017-03-14 14:55 UTC
Labels: bug, needrepro, priority-high, triaged

**Comment by victorsosa** [comment] 2017-04-10 21:28
I spoke too soon; I still getting the issue in version 1.2.7., also to be able to connect to the device, I have to retry like more than 10 times before it attach to the device and when that happens I got this error in console that doesn't affect the debugging process but it is relate to the codova-plugin code:

```
Error processing "variables": TypeError: Cannot read property 'length' of undefined
    at trimProperty (/home/vns/.vscode/extensions/vsmobile.cordova-tools-1.2.7/node_modules/vscode-chrome-debug-core/out/src/chrome/variables.js:167:18)
    at propertyPreviewToString (/home/vns/.vscode/extensions/vsmobile.cordova-tools-1.2.7/node_modules/vscode-chrome-debug-core/out/src/chrome/variables.js:161:19)
    at props.map.prop (/home/vns/.vscode/extensions/vsmobile.cordova-tools-1.2.7/node_modules/vscode-chrome-debug-core/out/src/chrome/variables.js:151:43)
    at Array.map (native)
    at getObjectPreview (/home/vns/.vscode/extensions/vsmobile.cordova-tools-1.2.7/node_modules/vscode-chrome-debug-core/out/src/chrome/variables.js:151:14)
    at Object.getRemoteObjectPreview (/home/vns/.vscode/extensions/vsmobile.cordova-tools-1.2.7/node_modules/vscode-chrome-debug-core/out/src/chrome/variables.js:194:17)
    at CordovaDebugAdapter.createObjectVariable (/home/vns/.vscode/extensions/vsmobile.cordova-tools-1.2.7/node_modules/vscode-chrome-debug-core/out/src/chrome/chromeDebugAdapter.js:1359:33)
    at CordovaDebugAdapter.remoteObjectToVariable (/home/vns/.vscode/extensions/vsmobile.cordova-tools-1.2.7/node_modules/vscode-chrome-debug-core/out/src/chrome/chromeDebugAdapter.js:1302:33)
    at Promise.all.args.map (/home/vns/.vscode/extensions/vsmobile.cordova-tools-1.2.7/node_modules/vscode-chrome-debug-core/out/src/chrome/variables.js:32:62)
    at Array.map (native)


```

**Comment by annayafi** [comment] 2017-04-29 19:26
I had the same issue with a samsung galaxy tab s10.5 and I finally ran command line ionic run android first, and then Run on android device started to work within vs code.

**Comment by victorsosa** [comment] 2017-04-29 19:28
@annayafi I will try that

**Comment by sekhuat** [comment] 2017-06-25 11:23
Hi All,

I also had faced the same issue on "Unable to find localabstract name of cordova app". I had keep trying difference configuration on the launch.json but still not no avail.

Finally I made my hand dirty by digging into the VSCode cordova extenstion. In the folder ~/.vscode/extensions/vsmobile.cordova-tools-1.2.7/out/src/debugger I had modify the file extension.js on the function "cordovaStartCommand" (around line 63) as below:
<pre>
function cordovaStartCommand(args, cordovaRootPath) {
    let cliName = cordovaProjectHelper_1.CordovaProjectHelper.isIonicProject(cordovaRootPath) ? 'cordova' : 'cordova';
    let commandExtension = os.platform() === 'win32' ? '.cmd' : '';
    let command = cliName + commandExtension;
    console.warn('\nCommand: ' + command);
    return child_process.spawn(command, args, { cwd: cordovaRootPath });
}
</pre>
Change the first line in the function on the portion `'ionic' : 'cordova'` to `'cordova' : 'cordova'` and save the file.

Also, make sure your launch.json have the similar setting:

<pre>
 {
   "version": "0.2.0",
   "configurations": [
     {
         "name": "Run Android on device",
         "type": "cordova",
         "request": "launch",
         "platform": "android",
         "port": 9222,
         "target": "device",
         "sourceMaps": true,
         "cwd": "${workspaceRoot}",
         "ionicLiveReload": false,
         "appStepLaunchTimeout": 60000
     }
   ]
 }
</pre>
Make sure the appStepLaunchTimeout is large enough for the app to launch. For normal device 60000 should be enough.

Hope this will help those who still face the same issue. Thank you.

**Comment by victorsosa** [comment] 2017-06-25 14:18
@sekhuat I did that and got the same result as before. "Unable to find localabstract name of cordova app"

I have to retry like more than 10 times before it attach to the device as before.

**Comment by victorsosa** [comment] 2017-06-25 15:42
Guys I found the issue; the PR #262 is not correctly merge in the release 1.2.7; I apply that fix and now is working properly.

**Comment by victorsosa** [comment] 2017-06-25 16:21
This could be working fine in the next release

**Comment by sekhuat** [comment] 2017-06-26 01:07
@victorsosa make sure the appStepLaunchTimeout is having a value large enough. This is the time allow for the app to launch in your device before the extension script try to look for its pid in thr device. If the value is too short and the app is not fully launch in device then the script wont be able to locate the pid of the app, thus give you error.

**Comment by victorsosa** [comment] 2017-06-26 01:45
@sekhuat appStepLaunchTimeout is for iOS platform

**Comment by sekhuat** [comment] 2017-06-26 05:32
@victorsosa  Thanks for your info on the appStepLaunchTimeout.

Although the previous solution works for me, it has an issue on pushing the newly compiled apk to the device. Which means even I can debug the app via VSCode but somehow the apk load into the device is the old version of apk that is original in the device.

I had further make changes on the extension.js and now it work perfectly for me even with live reload.

I had changed back the `'cordova' : 'cordova'` back to `'ionic' : 'cordova'`. However I had added in the following line `args.unshift('cordova');` just before the command is executed. Below is the function I had modified in the extension.js.
<pre>
exports.cordovaRunCommand = cordovaRunCommand;
function cordovaStartCommand(args, cordovaRootPath) {
    let cliName = cordovaProjectHelper_1.CordovaProjectHelper.isIonicProject(cordovaRootPath) ? <b>'ionic' : 'cordova'</b>;
    let commandExtension = os.platform() === 'win32' ? '.cmd' : '';
    let command = cliName + commandExtension;
    <b>args.unshift('cordova');</b>
    return child_process.spawn(command, args, { cwd: cordovaRootPath });
}
</pre>

**Comment by isupovs** [comment] 2017-07-13 14:01
Hi, guys. I still get the issue. I'm using Ionic v1 app.
I've tried to apply path suggested by @victorsosa 

Your system information:

Cordova CLI: 7.0.1
Ionic CLI Version: 2.2.1
Ionic App Lib Version: 2.2.0
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Windows 10
Node Version: v6.9.4
Xcode version: Not installed

**Comment by victorsosa** [comment] 2017-07-13 14:23
Hi, @isupovs 
I also increase the timeout to 30seg in this line too, with that final fix it really worked for me everytime.

`return CordovaDebugAdapter.retryAsync(findAbstractNameFunction, (match) => !!match, 5, 1, **30000**, 'Unable to find localabstract name of cordova app')`

https://github.com/Microsoft/vscode-cordova/blob/master/src/debugger/cordovaDebugAdapter.ts#L375

**Comment by isupovs** [comment] 2017-07-13 16:25
Hi, @victorsosa 
It doesn't work for me as well.

**Comment by victorsosa** [comment] 2017-07-14 12:47
@isupovs there are two lines that need this change to:
`line.split(/[ \r]+/)`
please double check again the cordovaDebugAdapter.ts file.

**Comment by isupovs** [comment] 2017-07-14 13:38
@victorsosa, oh thanks! It works!

**Comment by victorsosa** [comment] 2017-07-14 13:52
@isupovs glad to know

**Comment by p595285902** [comment] 2017-07-30 17:52
I am getting this error with 1.2.8 with android emulator.
Works fine with device but not emulator.
`{
            "name": "Run Android on emulator",
            "type": "cordova",
            "request": "launch",
            "platform": "android",
            "target": "emulator",
            "port": 9222,
            "sourceMaps": true,
            "cwd": "${workspaceRoot}",
            "ionicLiveReload": false
        },`

**Comment by jaoel** [comment] 2017-08-07 09:44
I had the same issue and got the error `Unable to find localabstract name of cordova app` when trying to debug on my OnePlus 3t. After some digging I found that, for some reason on my device, `appPackageName` is not found in the 9th column of the `ps` command.

As a workaround i changed the following:
`src/cordovaDebugAdapter.ts:327`
```ts
return Q.all([packagePromise, adbDevicesResult]).spread((appPackageName, targetDevice) => {
            let getPidCommandArguments = ['-s', targetDevice, 'shell', 'ps', '|', 'grep', appPackageName];
            let getSocketsCommandArguments = ['-s', targetDevice, 'shell', 'cat /proc/net/unix'];

            let findAbstractNameFunction = () =>
                // Get the pid from app package name
                this.runAdbCommand(getPidCommandArguments, errorLogger)
                .then((psResult) => {
                    const lines = psResult.split('\n');
                    for (const line of lines) {
                        const fields = line.split(/[ \r]+/);
                        return fields[1];
                    }
                })
        ...
```
With this change I'm able to connect to the device and debugging works as expected.

**Comment by vladimir-kotikov** [comment] 2017-08-11 14:21
@p595285902 could you please provide the following information to debug your case:
1. ouput of the following 2 commands (where `device_id` is device name as shown by `adb devices`):
  ```
  adb -s <device_id> shell ps
  adb -s <device_id> shell "cat /proc/net/unix"
  ```
2. your application id (package name)

Thanks

**Comment by vladimir-kotikov** [comment] 2017-08-11 14:22
@jaoel, your input would also be appreciated as it looks like you've ran into the same problem

**Comment by vladimir-kotikov** [comment] 2017-08-16 11:28
@p595285902, @jaoel guys, any apdates? Were you able to figure out what's `adb` output look like?

**Comment by jaoel** [comment] 2017-08-17 10:16
@vladimir-kotikov 
The output of `ps` follows this pattern
```
USER      PID   ADJ   PPID  VSIZE  RSS   WCHAN              PC  NAME
root      1     -1000 0     16620  2520  SyS_epoll_ 0000000000 S /init
root      2     0     0     0      0       kthreadd 0000000000 S kthreadd
root      3     0     2     0      0     smpboot_th 0000000000 S ksoftirqd/0
...
u0_a144   14403 901   2306  3250008 254180 SyS_epoll_ 0000000000 S com.mytestapp.app.ionic
```
and `proc/net/unix` 
```
Num       RefCount Protocol Flags    Type St Inode Path
0000000000000000: 00000002 00000000 00000000 0002 01 39939 /dev/socket/qmux_radio/rild_sync_1
0000000000000000: 00000002 00000000 00000000 0002 01  8024 @suilst
0000000000000000: 00000002 00000000 00010000 0001 01 38149 /dev/socket/ims_datad
0000000000000000: 00000002 00000000 00000000 0002 01 35593 /dev/socket/qmux_radio/rild_sync_0
0000000000000000: 00000002 00000000 00010000 0001 01 16394 /dev/socket/vold
0000000000000000: 00000002 00000000 00010000 0001 01 34318 /dev/socket/cnd
0000000000000000: 00000002 00000000 00010000 0001 01 16399 /dev/socket/cryptd
...
```

**Comment by vladimir-kotikov** [comment] 2017-08-17 14:49
@jaoel, thanks. Regarding the second one - it's not full output, right? Can you please post a full one, or if it's too long - upload it to any storage service and send a link.

Just to explain what I'm looking for - while attaching extension debugger to WebView on your device [we first fetch application's PID](https://github.com/Microsoft/vscode-cordova/blob/master/src/debugger/cordovaDebugAdapter.ts#L346) and then use it to find remote port on your device where WebView debugger listening for connections. To find this [we look for line in `/proc/net/unix` that has the following flags `Flags=00010000`,  `St=01` and `Path` matching a couple of known patterns](https://github.com/Microsoft/vscode-cordova/blob/master/src/debugger/cordovaDebugAdapter.ts#L367-L389). So while the first snippet looks good - at least we're able to find out app's PID there - I wonder if the problem is that we just can't fetch correct remote port.

**Comment by jaoel** [comment] 2017-08-17 21:42
@vladimir-kotikov [Right here](https://github.com/Microsoft/vscode-cordova/blob/master/src/debugger/cordovaDebugAdapter.ts#L345-L356) is where things go wrong. Considering the `ps` output
`u0_a144   14403 901   2306  3250008 254180 SyS_epoll_ 0000000000 S com.mytestapp.app.ionic`
the value at `fields[8]` will be `S` and not at all equal to `appPackageName`, which instead is found in `fields[9]`. So I hacked together a workaround to bypass all this by calling `ps | grep appPackageName` and get the correct line from `ps` that way.

The following line exists in `proc/net/unix`
`0000000000000000: 00000002 00000000 00010000 0001 01 17098872 @webview_devtools_remote_14403`
and is correctly found once I find the PID through the workaround mentioned above, so I believe this part is working as intended, but [here is the full output](https://pastebin.com/HwH3mSmp) just in case.

**Comment by vladimir-kotikov** [comment] 2017-08-18 09:50
My bad, I didn't notice that. @jaoel thanks for pointing out - I believe that @iTOYS has already fixed this in #306 - we'll release updated version with that patch soon

**Comment by victorsosa** [comment] 2017-11-10 14:02
@vladimir-kotikov I tested v1.3.0 and the patch #306 is not working (this was working before); I am getting "Unable to find localabstract name of cordova app" back again

**Comment by vladimir-kotikov** [comment] 2017-11-13 18:26
@victorsosa, I'm sorry but I'm not working on VSCode extensions anymore. Pinging @iTOYS to see if he could help

**Comment by victorsosa** [comment] 2017-11-13 18:36
@vladimir-kotikov thanks, I just tested it today and it seems to be working fine.

**Comment by marco-sampaiopereira** [comment] 2019-04-11 17:14
The way that I resolved it was: In your device cell phone, go to configurations, aplication, find your aplication... in my case it was as unable.. so, I desinstalled it... after I tryied to run again in vscode in debug and it worked
