### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by dinsairbnb** [Microsoft/vscode-cordova#515] opened 2019-04-05 17:39 UTC
- Issue Type: `Performance`
- Extension Name: `cordova-tools`
- Extension Version: `1.8.0`
- OS Version: `Linux x64 4.15.0-47-generic`
- VSCode version: `1.32.3`

:warning: Make sure to **attach** this file from your *home*-directory: `/home/miquel/vsmobile.cordova-tools-unresponsive.cpuprofile.txt` :warning:

Find more details here: https://github.com/Microsoft/vscode/wiki/Explain:-extension-causes-high-cpu-load

**Comment by ruslan-bikkinin** [comment] 2019-04-08 14:00
Closed as duplicate of #517

**Closed by ruslan-bikkinin** 2019-04-08 14:00 UTC
