### ISSUE TITLE
[Issue] [Cordova Tool] Unable to "Attach to running iOS on device" , "Run iOS on simulator", & "Run iOS on device" after updated the VS Code from version 0.10.9 to version 0.10.10

### ISSUE THREAD

**Issue by saintc0d3r** [Microsoft/vscode-cordova#49] opened 2016-03-08 05:17 UTC
**Symptom** 
When the Visual Studio Code has been installed with Cordova Tools plugin and has been upgraded from version 0.10.9 to version 0.10.10, running or debugging cordova /ionic app through options "Attach to running iOS on device", "Run iOS on simulator" & "Run iOS on device" returns **[cordova-debug-adapter] TypeError: Path must be a string. Received undefined** error

**Replication Steps**
1. Ensure that the Visual Studio code's version is earlier than version 0.10.10 and has been installed with cordova tools extension.
2. Open an Ionic project's folder then run it through option "Run iOS on simulator" or "Run iOS on device" . Confirm that no error happened and the iOS app runs successfully.
3. Update the Visual Studio Code to version 0.10.10 through clicking update notification on top of VS Code's window.
4. Restart the Visual Studio Code and repeat step 2. Confirm that an error **[cordova-debug-adapter] TypeError: Path must be a string. Received undefined** happens.

**System Environment**
- Cordova CLI: 6.0.0
- Gulp version:  CLI version 3.9.0
- Gulp local:   Local version 3.9.0
- Ionic Version: 1.1.1
- Ionic CLI Version: 1.7.14
- Ionic App Lib Version: 0.7.0
- ios-deploy version: 1.8.0 
- ios-sim version: 5.0.6 
- OS: Mac OS X El Capitan
- Node Version: v5.7.1
- Xcode version: Xcode 7.2 Build version 7C68 

![image](https://cloud.githubusercontent.com/assets/1336147/13592741/13967336-e530-11e5-962f-74066c2a42ae.png)

**Comment by MSLaguana** [comment] 2016-03-08 05:22
Thanks for reporting this! We've been investigating this in #48, but it's always good to get more data. I'll see if I can reproduce the issue with your setup.

**Comment by raphxyz** [comment] 2016-03-08 08:48
same issue with android! :(

**Comment by burtonsmith** [comment] 2016-03-08 13:26
I am also having the same problem. It started after I installed the latest update for VS Code.

**Comment by DickvdBrink** [comment] 2016-03-08 15:07
See https://github.com/Microsoft/vscode-cordova/issues/48#issuecomment-193814003 with a workaround :)

**Comment by saintc0d3r** [comment] 2016-03-08 15:13
Hello All,

I did the fix suggested by @DickvdBrink by adding "cwd": "${cwd}", entry  on each objects defined within launch.json then tried to replicate the issue and the error did not happen. All things go well now. Here's the complete content of my launch.json:

{
	"version": "0.2.0",
	"configurations": [
		{
			"name": "Run Android on device",
            "cwd": "${cwd}",
			"type": "cordova",
			"request": "launch",
			"platform": "android",
			"target": "device",
			"port": 9222,
			"sourceMaps": true
		},
		{
			"name": "Run iOS on device",
            "cwd": "${cwd}",
			"type": "cordova",
			"request": "launch",
			"platform": "ios",
			"target": "device",
			"port": 9220,
			"sourceMaps": true
		},
		{
			"name": "Attach to running android on device",
            "cwd": "${cwd}",            
			"type": "cordova",
			"request": "attach",
			"platform": "android",
			"target": "device",
			"port": 9222,
			"sourceMaps": true
		},
		{
			"name": "Attach to running iOS on device",
            "cwd": "${cwd}",            
			"type": "cordova",
			"request": "attach",
			"platform": "ios",
			"target": "device",
			"port": 9220,
			"sourceMaps": true
		},
		{
			"name": "Run Android on emulator",
            "cwd": "${cwd}",            
			"type": "cordova",
			"request": "launch",
			"platform": "android",
			"target": "emulator",
			"port": 9222,
			"sourceMaps": true
		},
		{
			"name": "Run iOS on simulator",
            "cwd": "${cwd}",            
			"type": "cordova",
			"request": "launch",
			"platform": "ios",
			"target": "emulator",
			"port": 9220,
			"sourceMaps": true
		},
		{
			"name": "Attach to running android on emulator",
            "cwd": "${cwd}",            
			"type": "cordova",
			"request": "attach",
			"platform": "android",
			"target": "emulator",
			"port": 9222,
			"sourceMaps": true
		},
		{
			"name": "Attach to running iOS on simulator",
            "cwd": "${cwd}",            
			"type": "cordova",
			"request": "attach",
			"platform": "ios",
			"target": "emulator",
			"port": 9220,
			"sourceMaps": true
		}
	]
}

Cheers.

**Comment by Shreyash23** [comment] 2016-03-08 16:30
Had the same problem, adding
"cwd": "${cwd}"
into all the configurations fixed it.

Thanks @DickvdBrink .
Cheers

**Comment by MShamiltonia** [comment] 2016-03-08 17:25
Closing this issue as it's a dupe of [48](https://github.com/Microsoft/vscode-cordova/issues/48). We will be working on a permanent fix for the next update.

**Closed by MShamiltonia** 2016-03-08 17:25 UTC
Labels: bug
