### ISSUE TITLE
Unable to hit breakpoints in VS Code when running iOS/Android in simulator

### ISSUE THREAD

**Issue by dkhaupt** [Microsoft/vscode-cordova#287] opened 2017-07-01 12:59 UTC
I'm using VS Code 1.13.1 (May 2017) and Cordova Tools 1.2.7. This is my output of `ionic info`:
```
Cordova CLI: 7.0.1 
Ionic Framework Version: 3.2.1
Ionic CLI Version: 2.2.1
Ionic App Lib Version: 2.2.0
Ionic App Scripts Version: 1.3.7
ios-deploy version: 1.9.1 
ios-sim version: 6.0.0 
OS: macOS Sierra
Node Version: v7.4.0
Xcode version: Xcode 8.3.3 Build version 8E3004b
```
When I use the `Run iOS on simulator` debug option, the simulator launches and overall behaves as expected (, however I don't hit any breakpoints. I've tried adding the line `debugger;` as well, which also isn't working. 

Using the `Run Android on emulator` option behaves a bit differently. The emulator is launched, however the console output in VS Code only shows `Launching for android (This may take a while)...` even after it's launched, and I don't see any console output like I do with the iOS simulator. VS Code appears to be working as the app in the Android emulator is usable, but it's only when I close the emulator that I see more console output. Here's a snippet of what shows up after closing the emulator:
```
LAUNCH SUCCESS
No scripts found for hook "after_run".
Command finished with error code 0: adb -s,emulator-5584,shell,am,start,-W,-a,android.intent.action.MAIN,-ncom.dkhaupt.app/.MainActivity
App successfully launched
Attaching to android
List of devices attached
Unable to find emulator
```
Here are the `launch.json` entries for these 2 debugging configs:
```
       {
            "name": "Run Android on emulator",
            "type": "cordova",
            "request": "launch",
            "platform": "android",
            "target": "emulator",
            "port": 9222,
            "sourceMaps": true,
            "cwd": "${workspaceRoot}",
            "ionicLiveReload": false
        },
        {
            "name": "Run iOS on simulator",
            "type": "cordova",
            "request": "launch",
            "platform": "ios",
            "target": "iPhone-5",
            "port": 9220,
            "sourceMaps": true,
            "cwd": "${workspaceRoot}",
            "ionicLiveReload": false
        }
```

From what information I could find, this seemed to be a relatively common issue throughout 2016 that was addressed by some updates regarding the source mapping- which I think is now handled by the `"sourceMaps": true` entry in the launch configurations. 

Issue #286 references some new commits since the last release, including one about debugging on iOS 10- apologies if that commit fixes my issue and I've opened a new one needlessly. If that's the case, how would I go about making use of it? I assume I'd need to fork the repo and build off of master, but I'm not sure how to point VS Code to something like that.

**Comment by vladimir-kotikov** [comment] 2017-08-11 08:53
@dkhaupt, sorry for late response. Not sure if the issue is still relevant but in case if it is - we recently released a new version of extension (1.2.8) which addresses a lot of different debugging problems. Could you please try upgrading and let us know if the problem still exists with the new version.

Thanks

**Comment by vladimir-kotikov** [comment] 2017-08-18 10:45
@dkhaupt, just a friendly ping if this issue is still relevant and reproduces with the latest version of extension?

**Comment by dkhaupt** [comment] 2017-08-18 11:40
Thanks for getting back to me- apologies on my own delay in responding. I'll see what I can do today as far as upgrading & debugging!

**Comment by vladimir-kotikov** [comment] 2017-08-18 12:24
@dkhaupt, thanks

**Comment by vladimir-kotikov** [comment] 2017-09-07 09:53
@dkhaupt pinging once more. Have you had a chance to verify whether it works for you?

**Comment by vladimir-kotikov** [comment] 2017-10-09 10:50
Closing this. @dkhaupt, if you're still running into this, feel free to reopen or create a new issue

**Closed by vladimir-kotikov** 2017-10-09 10:50 UTC
Labels: bug, needrepro, triaged
