### ISSUE TITLE
Debug console error Unimplemented console API: undefined

### ISSUE THREAD

**Issue by erenozm** [Microsoft/vscode-cordova#201] opened 2016-10-28 22:14 UTC
`Unimplemented console API: undefined`

hello, 

I am getting this error message instead of any exception messages or console.log messages when i try to debug ionic cordova project on an android device.  App is working fine on device.

do you have any ideas how to solve it?

thank you.

**Comment by MSLaguana** [comment] 2016-10-28 23:32
When do you get that message? Is VSCode still in debug mode, with the arrow and the pause symbol etc? Is that message printed to the debug console, and is it the only thing there?

If you try debugging the Simulate target, does that have the same error?

**Comment by erenozm** [comment] 2016-10-28 23:54
error message is printing to the debug console instead of console.log messages and error codes. yes VSCode is still in debug mode and the app works fine. i am having the same result with "Simulate Android in browser" option. on android emulator everything works fine.

`Launching for android (This may take a while)...
App successfully launched
Attaching to android
Forwarding debug port
Attaching to app.
Unimplemented console API: undefined
Unimplemented console API: undefined
Unimplemented console API: undefined
Unimplemented console API: undefined
Unimplemented console API: undefined`

thank you

**Comment by MSLaguana** [comment] 2016-10-29 00:02
Ah, it looks like you've hit a bug in vscode-chrome-debug, the underlying library which we use to debug the webviews: https://github.com/Microsoft/vscode-chrome-debug-core/blob/master/src/chrome/consoleHelper.ts#L46

It would be helpful if you could make a tweak to the extension so we can try to find out the cause:
* Go to your vscode extension directory, either `C:\Users\<user>\.vscode\extensions\` or `~/.vscode/extensions`, then go to `vsmobile.cordova-tools-1.2.3/node_modules/vscode-chrome-debug-core/out/src/chrome/` and open up `consoleHelper.js`.
* Look around line 37 for `outputText = 'Unimplemented console API: ' + m.type;`
* change that to `outputText = 'Unimplemented console API: ' + JSON.stringify(m);`

Once you've done that, please let us know what errors you get now. There may be some change or edge-case in the debugging protocol that we weren't aware of.

**Comment by erenozm** [comment] 2016-10-29 00:23
thank you for your quick response MSLaguana.

here are the messages.

```
Unimplemented console API: {"source":"console-api","level":"log","text":"LANGUAGE SUCCESS -> en","url":"file:///android_asset/www/js/app.js","line":119,"column":21}
Unimplemented console API: {"source":"console-api","level":"log","text":"No Problem in db!","url":"file:///android_asset/www/js/app.js","line":105,"column":27}
Unimplemented console API: {"source":"console-api","level":"log","text":"OPEN database: db.db","url":"file:///android_asset/www/plugins/cordova-sqlite-storage/www/SQLitePlugin.js","line":175,"column":15}
Unimplemented console API: {"source":"console-api","level":"log","text":"OPEN database: db.db - OK","url":"file:///android_asset/www/plugins/cordova-sqlite-storage/www/SQLitePlugin.js","line":179,"column":19}
Unimplemented console API: {"source":"console-api","level":"log","text":"DB opened: db.db","url":"file:///android_asset/www/plugins/cordova-sqlite-storage/www/SQLitePlugin.js","line":80,"column":15}
```

`outputText = m.text; `
this is enough for me for now :)

**Comment by verylongword** [comment] 2016-11-05 08:02
I also encounter this problem
IN Visual Studio Code debug console:

App successfully launched
Attaching to android
Forwarding debug port
Attaching to app.
Unimplemented console API: undefined
Unimplemented console API: undefined
Unimplemented console API: undefined
Unimplemented console API: undefined
Unimplemented console API: undefined
Unimplemented console API: undefined
Unimplemented console API: undefined
Unimplemented console API: undefined
-----------------------------------------
Unfortunately for me I have real bug(s)  in my code so this attempt at debugging on my phone gives me a blank screen. 
Any suggestions for a workaround would be much appreciated

**Comment by MSLaguana** [comment] 2016-11-05 17:03
For a temporary workaround, you can follow the steps in https://github.com/Microsoft/vscode-cordova/issues/201#issuecomment-257056099 and then set something like `outputText = m.text`

**Comment by myth815** [comment] 2016-11-14 04:25
![image](https://cloud.githubusercontent.com/assets/1798360/20253340/75061cca-aa65-11e6-9a23-b1724cb17b33.png)

**Comment by julientype** [comment] 2016-11-24 23:58
AHHHH that worked..... MSLaguana 
now even when i device load for cordove it worked..... but no brake points in it....
works in chrome now.....

tk julien
http://3taccount.com

**Comment by zompad** [comment] 2016-11-30 21:49
Yes I have encountered the same as issue and have done the @MSLanguana workaround which I think is very "dirty".

Like @julientype I cannot do break points, I get a grey "breakpoint unverified" in the left gutter.

Please can someone in Microsoft help/fix ... please.

**Comment by KinsonDigital** [comment] 2016-12-19 16:09
Is this a fix that is going to be released anytime soon?

**Comment by MSLaguana** [comment] 2016-12-19 16:21
It's something that we're looking into, but it isn't as simple as you might hope. The correct fix for this is to update a dependency we have to a newer version (vscode-chrome-debug-core specifically) but between the version we use and the latest version there were some breaking changes, so we need to resolve those before we can fix the problem properly.

**Comment by KinsonDigital** [comment] 2016-12-19 19:57
Absolutely understandable.  Thank you so much @MSLaguana.

**Comment by jmesa-sistel** [comment] 2017-01-11 17:15
Any news?

**Comment by MSLaguana** [comment] 2017-01-11 17:21
I have a potential fix in #227 but I was intending to test it out a bit more before publishing. If you would like to check out the repo and see if it fixes things for you without introducing other issues, that'd be helpful and give me more confidence in putting out an update with the fix.

**Comment by jmesa-sistel** [comment] 2017-01-11 17:22
@MSLaguana 
Ok, I'll do it, but I have to do it tomorrow, thanks for your fast response.

**Comment by jmesa-sistel** [comment] 2017-01-13 11:36
I have installed the last code in my Windows10 and the problem persists.
`Unimplemented console API: {"source":"console-api","level":"log","text":"Angular 2 is running in the development mode. Call enableProdMode() to enable the production mode.","url":"http://192.168.114.208:8100/build/main.js","line":1845,"column":13}`

**Comment by jmesa-sistel** [comment] 2017-01-13 13:16
@MSLaguana 
If I change in `cordovaDebugAdapter.ts`
`return super.attach(processedAttachArgs);`
by
`return super.attach(attachArgs);`
Now everything works, but I guess you want to merge processedAttachArgs & attachArgs but I am not sure.

**Comment by MSLaguana** [comment] 2017-01-13 16:03
Ah thanks for testing that out. I had been testing with the simulate target, but I had forgotten we had special cases for android and iOS targets. I'll investigate that further and get a fix in.

**Closed** 2017-01-13 20:27 UTC
Labels: copiedtobacklog, triaged

**Comment by MSLaguana** [comment] 2017-01-13 21:21
I've published a new build which should have these fixes.
