### ISSUE TITLE
detectArchitecture timeout is too short.

### ISSUE THREAD

**Issue by GimpArm** [microsoft/vscode-cordova#616] opened 2020-04-29 09:58 UTC
## Actual Behavior

Debugging fails to start

## Expected Behavior

Debugging starts and connects

## Software versions
- Cordova VS Code extension version: 1.9.3
- VSCode version: 1.44.2
- OS platform and version: Windows 10
- NodeJS version: v12.16.2
- Cordova version: 9.0.0
- Cordova-Android/iOS/Windows version: Android 8.1.0

## Outputs (Include if relevant)
- Output of the Debug Console (View -> Toggle Debug Console):
```
Command finished with error code 0: adb devices
Running adb shell command "cat /proc/cpuinfo" on target ce071827f219c13701...

Command finished with error code ENOENT: killall adb
Device communication timed out. Try unplugging & replugging the device.
CordovaError: Device communication timed out. Try unplugging & replugging the device.
    at Object.module.exports.detectArchitecture (D:\workspace\Git\store-logistics-app\build-tmp\cordova\cordova\platforms\android\cordova\lib\build.js:209:35)
    at D:\workspace\Git\store-logistics-app\build-tmp\cordova\cordova\platforms\android\cordova\lib\device.js:64:22
    at _fulfilled (D:\workspace\Git\store-logistics-app\node_modules\q\q.js:854:54)
    at D:\workspace\Git\store-logistics-app\node_modules\q\q.js:883:30
    at Promise.promise.promiseDispatch (D:\workspace\Git\store-logistics-app\node_modules\q\q.js:816:13)
    at D:\workspace\Git\store-logistics-app\node_modules\q\q.js:624:44
    at runSingle (D:\workspace\Git\store-logistics-app\node_modules\q\q.js:137:13)
    at flush (D:\workspace\Git\store-logistics-app\node_modules\q\q.js:125:13)
    at processTicksAndRejections (internal/process/task_queues.js:79:11)
Command finished with error code 0: adb -s,ce071827f219c13701,shell,cat,/proc/cpuinfo
'cordova.cmd run android --device --verbose --no-update-notifier' failed with exit code 1
```
- Output of the Developer Tools console (Help -> Toggle Developer Tools -> Select Console tab):
```
  ERR [cordova-tools] Error processing "launch": 'cordova.cmd run android --device --verbose --no-update-notifier' failed with exit code 1: Error: [cordova-tools] Error processing "launch": 'cordova.cmd run android --device --verbose --no-update-notifier' failed with exit code 1
    at t.RawDebugSession.handleErrorResponse (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:3044:67)
    at file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:3043:339
    at async t.RawDebugSession.launchOrAttach (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:3036:982)
    at async e.launchOrAttach (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:6271:914)
    at async e.launchOrAttachToSession (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:6296:932)
    at async file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:6300:326
```

**Comment by GimpArm** [comment] 2020-04-29 09:59
What I can tell the timeout is 1000 ms before throwing the error. Sometimes the device can take 2 or 3 seconds to completely finish the adb shell command call. Changing the timeout to 10000 ms makes everything work. I suggest you increase this timeout to allow for devices on networks and slower connections or find a better way to determine if there really is a connection issue.

build.js
`return helper().timeout(1000, new CordovaError('Device communication timed out. Try unplugging & replugging the device.')).then(null, function (err) {`

**Comment by SounD120** [comment] 2020-04-29 10:04
Hi @GimpArm and thanks for reaching us. Does this issue reproduces when you run the command below from your terminal without VS Code usage?
```
cordova.cmd run android --device --verbose --no-update-notifier
```

**Comment by GimpArm** [comment] 2020-04-29 10:39
Exact same error and stack trace. Increasing the timeout also makes that work.

**Comment by SounD120** [comment] 2020-04-29 10:58
If this reproduces even without the extension it means that this problem is inside Cordova framework, not the Cordova Tools VS Code extension. I recommend you to reach out to [Cordova repository](https://github.com/apache/cordova-android) and create new issue. You can mention the  [exact line that causes difficulties](https://github.com/apache/cordova-android/blob/master/bin/templates/cordova/lib/build.js#L213) in there or open a pull request to fix it. I am closing this issue as it was caused by the Cordova framework and not by the extension itself.

**Closed by SounD120** 2020-04-29 10:58 UTC
Labels: android, external
