### ISSUE TITLE
Simulate Browser Android Not Working

### ISSUE THREAD

**Issue by nandarbin** [Microsoft/vscode-cordova#285] opened 2017-06-22 07:59 UTC
I have a problem, every time I use simulate browser, I encounter xmlhttprequest responseText = "" or null problem. Can anyone help me ?
![untitled](https://user-images.githubusercontent.com/29623176/27423285-4a95d1f8-575b-11e7-812e-0b08c1be435d.png)

**Comment by alsorokin** [comment] 2017-08-03 07:17
hey @nandarbin can you please elaborate on your problem?
Does your developer console expose any exceptions?
Also a set of steps to reproduce the issue or a small sample app would be perfect.

**Comment by cocaybica** [comment] 2017-08-03 15:05
Hi, 

I have a similar issue, but in my case the console says:

**Couldn't find platform android in project, please install it using 'ionic platform add android'**

But making `ionic cordova platform add android` gives me:

**[INFO] Platform android already exists.**

I can launch without any problem using the option _Serve to the browser (ionic serve)_

My plugin version: 1.2.8

```
ionic info
    @ionic/cli-plugin-cordova       : 1.6.1
    @ionic/cli-plugin-ionic-angular : 1.4.1
    @ionic/cli-utils                : 1.7.0
    ionic (Ionic CLI)               : 3.7.0

global packages:

    Cordova CLI : 7.0.1

local packages:

    @ionic/app-scripts : 2.1.3
    Cordova Platforms  : android 6.2.3
    Ionic Framework    : ionic-angular 3.6.0

System:

    Android SDK Tools : 25.2.5
    Node              : v8.1.4
    OS                : Linux 4.10
    npm               : 5.0.3
```

**Comment by vladimir-kotikov** [comment] 2017-08-03 15:18
@cocaybica IMO your problem sound different. Could you please create a separate issue?

**Comment by cocaybica** [comment] 2017-08-03 15:29
OK

**Comment by vladimir-kotikov** [comment] 2017-08-11 08:45
@nandarbin I'm going to close this issue as it's not clear what the problem is and whether it is relevant to this extension. Feel free to reopen and add some additional details if you think this is an issue with extension.

**Closed by vladimir-kotikov** 2017-08-11 08:45 UTC
Labels: need-more-info, needrepro, question
